### ISSUE TITLE
Compile Error after v0.1.31 updated

### ISSUE THREAD

**Issue by forhonourlx** [reflex-dev/reflex#1071]
**Describe the bug**
Hi Pynecone Team,
I met some errors after v0.1.31 updated, how to solve this? Thanks
```
- info Using wasm build of next-swc
- warn Attempted to load @next/swc-win32-x64-gnu, but it was not installed
- warn Attempted to load @next/swc-win32-x64-msvc, but an error occurred: \\?\C:\Users\15800\Desktop\PeneconeDev\PreEnlight\.web\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node is not a valid Win32 application.
\\?\C:\Users\15800\Desktop\PeneconeDev\PreEnlight\.web\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
- warn Found lockfile missing swc dependencies, patching...
- event compiled client and server successfully in 1749 ms (1132 modules)
- wait compiling...
- event compiled client and server successfully in 181 ms (1132 modules)
- error Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async fetchPkgInfo (C:\Users\15800\Desktop\PeneconeDev\PreEnlight\.web\node_modules\next\dist\lib\patch-incorrect-lockfile.js:65:17)
    at async Promise.all (index 0)
    at async patchIncorrectLockfile (C:\Users\15800\Desktop\PeneconeDev\PreEnlight\.web\node_modules\next\dist\lib\patch-incorrect-lockfile.js:161:26) {
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'
  }
}
- wait compiling / (client and server)...
- event compiled client and server successfully in 1766 ms (1855 modules)
```

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.31
 - OS: win11
 - Browser (Optional): edge

**Comment by ElijahAhianyo** [comment]
this looks like a network error. Can you confirm if you still face this?
