### ISSUE TITLE
pc.select doesn't work with lists declared in State

### ISSUE THREAD

**Issue by jq6l43d1** [reflex-dev/reflex#1115]
**Describe the bug**
pc.select throws a type error when using it with a list declared in State.
```
Traceback (most recent call last):
  File "/home/user/code/pc-test/venv/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/pc.py", line 117, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/pc_test/pc_test.py", line 25, in <module>
    app.add_page(index, title="Select Example")
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/app.py", line 270, in add_page
    raise e
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/app.py", line 261, in add_page
    component = component if isinstance(component, Component) else component()
                                                                   ^^^^^^^^^^^
  File "/home/user/code/pc-test/pc_test/pc_test.py", line 14, in index
    pc.select(
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/components/forms/select.py", line 346, in create
    return super().create(*[], **props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/components/component.py", line 397, in create
    return cls(children=children, **props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/code/pc-test/venv/lib/python3.11/site-packages/pynecone/components/component.py", line 157, in __init__
    raise TypeError(
TypeError: Invalid var passed for prop options, expected type pynecone.vars.Var[typing.List[typing.Dict]], got value [{'label': "('name', 'options')", 'value': ('name', 'options'), 'variant': None}, {'label': "('type_', <class 'list'>)", 'value': ('type_', <class 'list'>), 'variant': None}, {'label': "('state', 'select_state')", 'value': ('state', 'select_state'), 'variant': None}, {'label': "('is_local', False)", 'value': ('is_local', False), 'variant': None}, {'label': "('is_string', False)", 'value': ('is_string', False), 'variant': None}] of type <class 'list'>.
```

**To Reproduce**
```
import pynecone as pc

class SelectState(pc.State):
    option: str = "No selection yet."
    options = ["Option 1", "Option 2", "Option 3"]

def index():
    return pc.vstack(
        pc.heading(SelectState.option),
        pc.select(
            SelectState.options,
            placeholder="Select an example.",
            on_change=SelectState.set_option,
            color_schemes="twitter",
        ),
    )

# Add state and page to the app.
app = pc.App(state=SelectState)
app.add_page(index, title="Select Example")
app.compile()
```

**Expected behavior**
The list should be rendered without error.

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.32
 - OS: Ubuntu 23.04
 
**Additional context**
I posted a similar bug that was fixed in a previous release: https://github.com/pynecone-io/pynecone/issues/821

**Comment by milochen0418** [comment]
Right now, we can only use the following way to use pc.select. 
The following code can works well. 
```python
import pynecone as pc
from typing import List
class State(pc.State):
    option: str = "No selection yet."

def index():
    return pc.vstack(
        pc.heading(State.option),
        pc.select(
            ["Option 1", "Option 2", "Option 3"],
            placeholder="Select an example.",
            on_change=State.set_option,
            color_schemes="twitter",
        ),
    )

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

If we use `@pc.var` here, we can make all running code halting after `pc run`
```python
import pynecone as pc
from typing import List
class State(pc.State):
    option: str = "No selection yet."
    options:List[str] = ["Option 1", "Option 2", "Option 3"]
    @pc.var
    def get_list(self) -> List[str]:
        return self.options
    pass

def index():
    return pc.vstack(
        pc.heading(State.option),
        pc.select(=
            State.get_list,
            placeholder="Select an example.",
            on_change=State.set_option,
            color_schemes="twitter",
        ),
    )

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Comment by masenf** [comment]
```python
import pynecone as pc
from typing import List

class State(pc.State):
    option: str = "No selection yet."
    options:List[str] = ["Option 1", "Option 2", "Option 3"]
    @pc.var
    def get_list(self) -> List[str]:
        return self.options

def index():
    return pc.vstack(
        pc.heading(State.option),
        pc.select(
            State.get_list,
            placeholder="Select an example.",
            on_change=State.set_option,
            color_schemes="twitter",
        ),
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()
```

☝️ this code is working for me on pynecone-0.1.31

On pynecone-0.1.32, i get a hang during compile, when I dump the stack trace it leaves me here:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/pc.py", line 118, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/pynecone-io/repro-1115/repro_1115/repro_1115.py", line 23, in <module>
    app.add_page(index)
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/app.py", line 261, in add_page
    component = component if isinstance(component, Component) else component()
                                                                   ^^^^^^^^^^^
  File "/Users/masen/code/pynecone-io/repro-1115/repro_1115/repro_1115.py", line 14, in index
    pc.select(
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/components/forms/select.py", line 340, in create
    for option in options:
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/vars.py", line 203, in __getitem__
    types._issubclass(self.type_, Union[List, Dict])
                                  ~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 348, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
```

I've had other problems with the new select component that was introduced in #1043 and subsequent fixups. It changed the API of the select component in a way that breaks the documentation and working examples.

And it looks like it's being reverted in #1123, so I that one merging will close this issue (for now).

In the meantime, I think sticking with 0.1.31 is probably the best bet if you rely on this functionality.

**Comment by masenf** [comment]
Closing. Code is working on reflex 0.3.4
