### ISSUE TITLE
Websocket not connecting when using Firefox

### ISSUE THREAD

**Issue by prakhar47b** [reflex-dev/reflex#1386]
**Describe the bug**
The websocket connects fine from Chrome but fails when using Firefox with the following error:

```
DEBUG:    = connection is CONNECTING
DEBUG:    ! invalid handshake
Traceback (most recent call last):
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 279, in read_http_request
    path, headers = await read_request(self.reader)
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/http.py", line 89, in read_request
    headers = await read_headers(stream)
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/http.py", line 160, in read_headers
    line = await read_line(stream)
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/http.py", line 197, in read_line
    raise SecurityError("line too long")
websockets.exceptions.SecurityError: line too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 165, in handler
    await self.handshake(
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 587, in handshake
    path, request_headers = await self.read_http_request()
  File "/home/prakhar/temp/reflex-test/venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 283, in read_http_request
    raise InvalidMessage("did not receive a valid HTTP request") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP request
DEBUG:    > HTTP/1.1 400 Bad Request
DEBUG:    > Date: Thu, 20 Jul 2023 12:09:19 GMT
DEBUG:    > Content-Length: 77
DEBUG:    > Content-Type: text/plain
DEBUG:    > Connection: close
DEBUG:    > [body] (77 bytes)
INFO:     connection failed (400 Bad Request)
DEBUG:    x closing TCP connection
DEBUG:    = connection is CLOSED
INFO:     connection closed
```

**To Reproduce**
Run the following and open it on Firefox:
```
class FormState(rx.State):
    test: str = ''

    def page_load(self):
        self.test = str(self.router_data)


@rx.route(route='/')
def index():
    return rx.vstack(
        rx.text(FormState.test),
        rx.button('Go', on_click=FormState.page_load)
    )

app = rx.App(state=FormState)
app.compile()
```

**Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Reflex Version: 0.2.0
 - OS: Ubuntu
 - Browser: Firefox 114.0.2 (64-bit)

**Comment by ElijahAhianyo** [comment]
Seems to work on the later versions of Firefox than the specified one(114.0.2), I assume this might be an issue from Firefox and not from us. Try updating your Firefox version to a later one (if you can). Feel free to reopen this issue or create another one if you do run into further issues.
