### ISSUE TITLE
 Automatically upgrade from Pynecone to Reflex Failed

### ISSUE THREAD

**Issue by forhonourlx** [reflex-dev/reflex#1393]
**Describe the bug**
`reflex init` auto upgrade fail, and I cannot locate where the file encode error is.
So any way to upgrade to Reflex?

```
(base) PS C:\Users\15800\Desktop\PeneconeDev\PreEnlightReflex> reflex init
───────────────────────────────────────────────────────────────────────── Initializing PreEnlightReflex ─────────────────────────────────────────────────────────────────────────
[15:51:00] Skipping bun installation on Windows.                                                                                                                    console.py:30
           Initializing the web directory.                                                                                                                          console.py:30
Pynecone project detected. Automatically upgrade to Reflex? [y/n]: y
Renaming pcconfig.py to rxconfig.py
Traceback (most recent call last):
  File "C:\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\reflex\reflex.py", line 48, in init
    prerequisites.migrate_to_reflex()
  File "C:\Users\15800\AppData\Roaming\Python\Python310\site-packages\reflex\utils\prerequisites.py", line 398, in migrate_to_reflex
    for line in file:
  File "C:\miniconda3\lib\fileinput.py", line 256, in __next__
    line = self._readline()
  File "C:\miniconda3\lib\fileinput.py", line 392, in _readline
    return self._readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 680: illegal multibyte sequence
```

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 0.2
 - OS: Windows11
 - Browser (Optional): Edge

**Comment by FHU-yezi** [comment]
Seems like you have the rxconfig.py in GBK encoding, so save it in UTF-8 encoding may fix this problem.
