### ISSUE TITLE
reflex container service - RUN reflex init fails

### ISSUE THREAD

**Issue by Jogenist** [reflex-dev/reflex#1512]
**Describe the bug**
While creating an container image from any reflex app, the build process fails at line 37 of the dockerfile (see error log).

**To Reproduce**
 - Create new reflex app (`reflex init`)
 - add requirements.txt and dockerfile from `docker-example`
 - run `docker build -t reflex-project:latest .` to build container image

**Expected behavior**
Container image should be build without errors.

**Specifics (please complete the following information):**
 - Python Version:  3.10.5
 - Reflex Version: 0.2.3
 - OS: Windows 10 Enterprise
 - Browser (Optional): -
 
**Error log**

```
[+] Building 37.9s (14/16)                                                                                      docker:default
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 856B                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:3.11-slim                                                       1.8s
 => [base 1/2] FROM docker.io/library/python:3.11-slim@sha256:36b544be6e796eb5caa0bf1ab75a17d2e20211cad7f66f04f6f5c9eeda  0.0s
 => [internal] load build context                                                                                         7.1s
 => => transferring context: 460.08MB                                                                                     7.0s
 => CACHED [base 2/2] RUN adduser --disabled-password reflex                                                              0.0s
 => CACHED [build 1/4] WORKDIR /app                                                                                       0.0s
 => CACHED [build 2/4] RUN python3 -m venv /app/venv                                                                      0.0s
 => [build 3/4] COPY . .                                                                                                  2.7s
 => [build 4/4] RUN pip install wheel     && pip install -r requirements.txt                                             14.7s
 => CACHED [runtime 1/1] RUN apt-get update && apt-get install -y     curl     && curl -fsSL https://deb.nodesource.com/  0.0s
 => CACHED [init 1/3] WORKDIR /app                                                                                        0.0s
 => [init 2/3] COPY --from=build /app/ /app/                                                                              3.8s
 => ERROR [init 3/3] RUN reflex init                                                                                      4.6s
------
 > [init 3/3] RUN reflex init:
2.774 ─────────────────────────────── Initializing app ───────────────────────────────
2.777 [08:49:37] Initializing the web directory.                         console.py:81
2.901 Exception in thread Thread-1 (initialize_bun):
2.901 Traceback (most recent call last):
2.901   File "/app/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2.901     yield
2.901   File "/app/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 62, in start_tls
2.901     raise exc
2.901   File "/app/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 57, in start_tls
2.901     sock = ssl_context.wrap_socket(
2.901            ^^^^^^^^^^^^^^^^^^^^^^^^
2.901   File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
2.901     return self.sslsocket_class._create(
2.901            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.901   File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
2.902     self.do_handshake()
2.902   File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
2.902     self._sslobj.do_handshake()
2.902 ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)
2.902
2.902 The above exception was the direct cause of the following exception:
2.902
2.902 Traceback (most recent call last):
2.902   File "/app/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2.902     yield
2.903   File "/app/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
2.903     resp = self._pool.handle_request(req)
2.903            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
2.903     raise exc
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
2.903     response = connection.handle_request(request)
2.903                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 92, in handle_request
2.903     raise exc
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 69, in handle_request
2.903     stream = self._connect(request)
2.903              ^^^^^^^^^^^^^^^^^^^^^^
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 149, in _connect
2.903     stream = stream.start_tls(**kwargs)
2.903              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2.903   File "/app/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 54, in start_tls
2.904     with map_exceptions(exc_map):
2.904   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2.904     self.gen.throw(typ, value, traceback)
2.904   File "/app/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2.904     raise to_exc(exc) from exc
2.904 httpcore.ConnectError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)
2.904
2.904 The above exception was the direct cause of the following exception:
2.904
2.904 Traceback (most recent call last):
2.904   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2.904     self.run()
2.904   File "/usr/local/lib/python3.11/threading.py", line 975, in run
2.905     self._target(*self._args, **self._kwargs)
2.905   File "/app/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 263, in initialize_bun
2.905     install_bun()
2.905   File "/app/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 360, in install_bun
2.905     download_and_run(
2.905   File "/app/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 290, in download_and_run
2.905     response = httpx.get(url)
2.905                ^^^^^^^^^^^^^^
2.905   File "/app/venv/lib/python3.11/site-packages/httpx/_api.py", line 189, in get
2.905     return request(
2.905            ^^^^^^^^
2.905   File "/app/venv/lib/python3.11/site-packages/httpx/_api.py", line 100, in request
2.906     return client.request(
2.906            ^^^^^^^^^^^^^^^
2.906   File "/app/venv/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
2.906     return self.send(request, auth=auth, follow_redirects=follow_redirects)
2.906            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.906   File "/app/venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
2.906     response = self._send_handling_auth(
2.906                ^^^^^^^^^^^^^^^^^^^^^^^^^
2.906   File "/app/venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
2.906     response = self._send_handling_redirects(
2.906                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.906   File "/app/venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
2.907     response = self._send_single_request(request)
2.907                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.907   File "/app/venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
2.907     response = transport.handle_request(request)
2.907                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2.907   File "/app/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
2.907     with map_httpcore_exceptions():
2.907   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2.907     self.gen.throw(typ, value, traceback)
2.907   File "/app/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2.907     raise mapped_exc(message) from exc
2.907 httpx.ConnectError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)
4.565 Error: Error during
4.566 Error: Run in with --loglevel debug to see the full error.
------
Dockerfile:37
--------------------
  35 |     ENV BUN_INSTALL="/app/.bun"
  36 |     COPY --from=build /app/ /app/
  37 | >>> RUN reflex init
  38 |
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c reflex init" did not complete successfully: exit code: 1
```

**Comment by Jogenist** [comment]
Update: It is possible to create the container, when deleting the `RUN reflex init` line from the Dockerfile, but then you cant start your container because the app is not initialized. I tried to run `reflex init` manually with the containers shell, but got the following error:

```
reflex@705e1f902d14:/app/ReflexContainerTest$ ls
ReflexContainerTest.py  __init__.py  __pycache__
reflex@705e1f902d14:/app/ReflexContainerTest$ reflex init
────────────────────────────────────────────────────────────────────────── Initializing ReflexContainerTest ───────────────────────────────────────────────────────────────────────────
Installing node failed with exit code 3
Version '18.17.0' not found - try `nvm ls-remote` to browse available versions.
Run with --loglevel debug  for the full log.
```
