### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by v479038280** [reflex-dev/reflex#1536]
I have installed npm ,why report such problem.
```

**reflex run**        
Warning: We strongly advise using Windows Subsystem for Linux (WSL) for optimal performance with reflex.
─────────────────────────────────────────────────────────────────────── Starting Reflex App ───────────────────────────────────────────────────────────────────────Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Traceback (most recent call last):
  File "D:\Program Files\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Folder_Share\reflex\chatapp\venv\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\reflex\reflex.py", line 172, in run
    setup_frontend(Path.cwd())
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\reflex\utils\build.py", line 181, in setup_frontend
    prerequisites.install_frontend_packages()
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\reflex\utils\prerequisites.py", line 371, in install_frontend_packages
    [get_install_package_manager(), "install", "--loglevel", "silly"],
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\reflex\utils\prerequisites.py", line 93, in get_install_package_manager
    return get_windows_package_manager()
  File "F:\Folder_Share\reflex\chatapp\venv\lib\site-packages\reflex\utils\prerequisites.py", line 78, in get_windows_package_manager
    raise FileNotFoundError("Reflex requires npm to be installed on Windows.")
FileNotFoundError: Reflex requires npm to be installed on Windows.
(venv) PS F:\Folder_Share\reflex\chatapp> **pip install npm**
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: npm in f:\folder_share\reflex\chatapp\venv\lib\site-packages (0.1.1)
Requirement already satisfied: 
```

**Comment by masenf** [comment]
The npm being referenced is that of nodejs: https://nodejs.org/en/download

Download the windows v18.17 installer and try again.
