### ISSUE TITLE
plotly example in documentation results in an error

### ISSUE THREAD

**Issue by nick-youngblut** [reflex-dev/reflex#1544]
**Describe the bug**

The [plotly example in documentation](https://reflex.dev/docs/library/graphing/plotly/) results in an error:

```
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<AsyncServer._handle_event_internal() done, defined at /Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/socketio/asyncio_server.py:522> exception=ValueError("Invalid path: ['state']")>
Traceback (most recent call last):
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/reflex/app.py", line 734, in on_event
    async for update in process(self.app, event, sid, headers, client_ip):
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/reflex/app.py", line 586, in process
    async for update in state._process(event):
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/reflex/state.py", line 675, in _process
    substate = self.get_substate(path)
  File "/Users/nyoungblut/opt/miniconda3/envs/reflex/lib/python3.9/site-packages/reflex/state.py", line 657, in get_substate
    raise ValueError(f"Invalid path: {path}")
ValueError: Invalid path: ['state']
```

It would be helpful to include more documentation on creating an actual functioning app that includes >=1 plotly plot.

**To Reproduce**

```
# my_app.py
from rxconfig import config
import reflex as rx
import plotly.express as px

df = px.data.gapminder().query("country=='Canada'")
fig = px.line(
    df,
    x="year",
    y="lifeExp",
    title="Life expectancy in Canada",
)

def index():
    return rx.plotly(data=fig, height="400px")

# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.9.16
 - Reflex Version: 0.2.3
 - OS: macOS 12.6.3
 - Browser (Optional): Chrome 115.0.5790.114

**Comment by nick-youngblut** [comment]
A possible updated example:

```python
from rxconfig import config
import reflex as rx
import pandas as pd
import plotly.express as px
from plotly.graph_objects import Figure

class State(rx.State):    
    df: pd.DataFrame = px.data.gapminder().query("country=='Canada'")
    fig: Figure = px.line(
        df,
        x="year",
        y="lifeExp",
        title="Life expectancy in Canada",
    )

def index():
    return rx.plotly(data=State.fig, height="400px")

app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by picklelo** [comment]
Thanks for bringing this up - we redeployed the site and this should be fixed. Please reopen if you still see this!
