### ISSUE TITLE
run app and then `ctrl+c` to stop it error: UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1563]
**Describe the bug**

I run app and then `ctrl+c` to stop it in VS Code console, the error pops up.
>reflex run
Warning: We strongly advise using Windows Subsystem for Linux (WSL) for optimal performance with reflex.
────────────────────────────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────────────────────────
DeprecationWarning: @rx.route is deprecated and is being replaced by @rx.page instead
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/2 0:00:00
Creating Production Build:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9 0:00:13
────────────────────────────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────────────────────────
App running at: http://localhost:3000
DeprecationWarning: @rx.route is deprecated and is being replaced by @rx.page instead
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/2 0:00:00
>[23:09:29] Reflex app stopped.                                                                                                                      console.py:81
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myname\AppData\Roaming\Python\Python311\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\reflex\reflex.py", line 179, in run
    processes.run_concurrently(*commands)
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\reflex\utils\processes.py", line 179, in run_concurrently
    task.result()
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\reflex\utils\exec.py", line 80, in run_frontend_prod
    run_process_and_launch_url([prerequisites.get_package_manager(), "run", "prod"])
  File "C:\Users\myname\AppData\Roaming\Python\Python311\site-packages\reflex\utils\exec.py", line 38, in run_process_and_launch_url
    for line in process.stdout:
  File "<frozen codecs>", line 322, in decode
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte**

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by evandeng2009** [comment]
Python 3.11.4
OS: Windows 11, and OS Language is Chinese
Reflex: 0.2.4.

Not sure if it is somehow related to https://github.com/reflex-dev/reflex/issues/1332 which was solvled by change file `C:\Program Files\Python311\Lib\fileinput.py`. Later then I changed it back and current issue `for line in process.stdout` occured.

**Comment by picklelo** [comment]
Closing for now, please reopen if it's still an issue.
