### ISSUE TITLE
Cannot serialize a list of PIL.Images, but a single PIL.Image is fine 

### ISSUE THREAD

**Issue by amcraig** [reflex-dev/reflex#1578]
**Describe the bug**
When trying to store or compute a list of PIL.Image.Image objects an error is thrown:
```
Task exception was never retrieved
future: <Task finished name='Task-281' coro=<AsyncServer._handle_event_internal() done, defined at /Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/socketio/asyncio_server.py:522> exception=TypeError("'Image' object is not iterable")>
Traceback (most recent call last):
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/reflex/app.py", line 737, in on_event
    self.emit(str(constants.SocketEvent.EVENT), update.json(), to=sid)
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/site-packages/reflex/base.py", line 33, in json
    return self.__config__.json_dumps(self.dict(), default=list)
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/craig/miniforge3/envs/decimer/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: 'Image' object is not iterable
```

**To Reproduce**
Try to save or compute a list of PIL.Image.Image objects to state.

**Expected behavior**
Since reflex can successfully serialize a single PIL.Image.Image from State, I don't see why we couldn't serialize an array.

**Specifics (please complete the following information):**
 - Python Version: 3.10.12
 - Reflex Version: 0.2.4
 - OS:  Darwin (M1)
 - Browser (Optional): Chrome

**Comment by wassafshahzad** [comment]
Can this issue be assigned to me ?

**Comment by wassafshahzad** [comment]
@amcraig Would you kindly be able to share a code snippet as well ?
