### ISSUE TITLE
BUG when run `reflex init`

### ISSUE THREAD

**Issue by lxbworld** [reflex-dev/reflex#1581]
**Describe the bug**
My network is ok. After `pip install reflex`, I run `reflex init`, then it prints this BUG.

**Screenshots**
────────────────────────────── Initializing test ───────────────────────────────
Traceback (most recent call last):
  File "/home/lxb/miniconda3/envs/reflex/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/lxb/miniconda3/envs/reflex/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lxb/miniconda3/envs/reflex/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/lxb/miniconda3/envs/reflex/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Specifics:**
 - Python Version: 3.11
 - Reflex Version: latest
 - OS: Ubuntu 20.04

**Comment by ElijahAhianyo** [comment]
Does this happen every time you do `reflex init`? Also, what's your miniconda version to repro this? Do you get the same error when you try with other virtual environments like poetry, pyenv, venv, etc?
