### ISSUE TITLE
sqlalchemy import error when executing "reflex init"

### ISSUE THREAD

**Issue by littledip** [reflex-dev/reflex#1592]
**Describe the bug**
Running "reflex init" from the command line results in the following error:

(spyder-env) C:\Users\johnd\my_app_name>reflex init
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnd\spyder-env\Scripts\reflex.exe\__main__.py", line 4, in <module>
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\__init__.py", line 8, in <module>
    from . import el as el
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\el\__init__.py", line 3, in <module>
    from .elements import *
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\el\elements\__init__.py", line 4, in <module>
    from reflex.el.element import Element
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\el\element.py", line 5, in <module>
    from reflex.components.component import Component
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\__init__.py", line 7, in <module>
    from .datadisplay import *
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\datadisplay\__init__.py", line 4, in <module>
    from .code import Code, CodeBlock
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\datadisplay\code.py", line 6, in <module>
    from reflex.components.forms import Button
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\forms\__init__.py", line 18, in <module>
    from .iconbutton import IconButton
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\forms\iconbutton.py", line 3, in <module>
    from reflex.components.typography.text import Text
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\typography\__init__.py", line 7, in <module>
    from .markdown import Markdown
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\components\typography\markdown.py", line 6, in <module>
    from reflex.compiler import utils
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\compiler\utils.py", line 23, in <module>
    from reflex.state import State
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\state.py", line 36, in <module>
    from reflex.utils import format, prerequisites, types
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\utils\prerequisites.py", line 23, in <module>
    from reflex import constants, model
  File "c:\users\johnd\spyder-env\lib\site-packages\reflex\model.py", line 15, in <module>
    import sqlmodel
  File "c:\users\johnd\spyder-env\lib\site-packages\sqlmodel\__init__.py", line 24, in <module>
    from sqlalchemy.schema import ThreadLocalMetaData as ThreadLocalMetaData
ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema' (c:\users\johnd\spyder-env\lib\site-packages\sqlalchemy\schema.py)

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.8.5
 - Reflex Version:  0.2.4
 - OS:  Windows 10
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by littledip** [comment]
Resolved, upgraded sqlmodel package.

**Comment by mwcoleman** [comment]
I had the same issue, resolved by `pip install sqlmodel --upgrade.` This kept the same version of sqlmodel (0.0.8), but downgraded SQLAlchemy from 2.0.20 to 1.4.41, which resolved the issue.
