### ISSUE TITLE
Programming errors by users do not indicate where it occurs in the user code

### ISSUE THREAD

**Issue by martinxu9** [reflex-dev/reflex#1610]
**Describe the bug**
If a user makes a mistake in the code, the errors thrown on the console/terminal do not indicate the relevant lines in the user code. Only the lines in the reflex library. This makes it difficult to pinpoint where the user mistake is.

**To Reproduce**

Follow the Reflex chat tutorial here https://reflex.dev/docs/tutorial/final-app/, in the `state.py` file `def answer():` function, instead of `yield`, type `yield self.chat_history`. It causes the error in the `Screenshots` below.

**Expected behavior**
The error stack should indicate where the programming error in the user code. Right now it is not only showing the lines in the reflex library. It'll be difficult to pinpoint/debug.

**Screenshots**
```
Task exception was never retrieved
future: <Task finished name='Task-70' coro=<AsyncServer._handle_event_internal() done, defined at /opt/homebrew/lib/python3.11/site-packages/socketio/asyncio_server.py:522> exception=TypeError('unsupported callable')>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 1369, in getfullargspec
    sig = _signature_from_callable(func,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 2449, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: ('how big is canada', '') is not a callable object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/reflex/app.py", line 734, in on_event
    async for update in process(self.app, event, sid, headers, client_ip):
  File "/opt/homebrew/lib/python3.11/site-packages/reflex/app.py", line 586, in process
    async for update in state._process(event):
  File "/opt/homebrew/lib/python3.11/site-packages/reflex/state.py", line 693, in _process
    events = fix_events(events, event.token)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/reflex/event.py", line 483, in fix_events
    e = e()
        ^^^
  File "/opt/homebrew/lib/python3.11/site-packages/reflex/event.py", line 56, in __call__
    fn_args = inspect.getfullargspec(self.fn).args[1:]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 1379, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```
**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.4
 - OS: MacOS
 - Browser (Optional):
 
**Additional context**

**Comment by masenf** [comment]
Thanks for reporting this issue. Tracking internally as REF-198
