### ISSUE TITLE
clock example broken on reflex-0.2.5a1

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1637]
* install reflex-0.2.5a1
* clone reflex-examples
* `cd clock`
* `reflex init`
* `reflex run`
* Open the browser and flip the switch

```
Traceback (most recent call last):
  File "/Users/masenf/code/reflex-dev/repro-fresca/reflex-examples/VENV-examples/lib/python3.8/site-packages/reflex/state.py", line 817, in _process_event
    yield self._check_valid(handler, events), True
  File "/Users/masenf/code/reflex-dev/repro-fresca/reflex-examples/VENV-examples/lib/python3.8/site-packages/reflex/state.py", line 766, in _check_valid
    raise TypeError(
TypeError: Your handler State.flip_switch must only return/yield: None, Events or other EventHandlers referenced by their class (not using `self`)
```

----------------

changing the code to use `State.tick` instead of `self.tick` as suggested does work... but why was this working on 0.2.4 and not now?

**Comment by masenf** [comment]
fixed via https://github.com/reflex-dev/reflex-examples/pull/138
