### ISSUE TITLE
ASGI error when saving files while running application

### ISSUE THREAD

**Issue by ZeD4805** [reflex-dev/reflex#1658]
This error has been happening for some days and I've just verified it also happens in someone else's project. I use poetry to handle my dependencies and to create the venv.

How to reproduce:
- Create a project
- Run it
- Alter the code and save

Error message:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 58, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/socketio/asyncio_server.py", line 398, in handle_request
    return await self.eio.handle_request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_server.py", line 257, in handle_request
    r = await self._handle_connect(environ, transport,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_server.py", line 430, in _handle_connect
    ret = await s.handle_get_request(environ)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 143, in _upgrade_websocket
    return await ws(environ)
           ^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 235, in __call__
    await self.handler(self)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 253, in _websocket_handler
    await asyncio.wait_for(writer_task, timeout=None)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 207, in writer
    await ws.close()
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 238, in close
    await self.asgi_send({'type': 'websocket.close'})
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 329, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 58, in __call__
    await self.engineio_server.handle_request(scope, receive, send)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/socketio/asyncio_server.py", line 398, in handle_request
    return await self.eio.handle_request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_server.py", line 257, in handle_request
    r = await self._handle_connect(environ, transport,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_server.py", line 430, in _handle_connect
    ret = await s.handle_get_request(environ)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
    return await getattr(self, '_upgrade_' + transport)(environ)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 143, in _upgrade_websocket
    return await ws(environ)
           ^^^^^^^^^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 235, in __call__
    await self.handler(self)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 253, in _websocket_handler
    await asyncio.wait_for(writer_task, timeout=None)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/asyncio_socket.py", line 207, in writer
    await ws.close()
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/engineio/async_drivers/asgi.py", line 238, in close
    await self.asgi_send({'type': 'websocket.close'})
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/home/USER/.cache/pypoetry/virtualenvs/reflex-asgi-error-e3a-i2Ie-py3.11/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 329, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
```

**Comment by masenf** [comment]
I just reproduced this issue inside a docker container, running in prod mode; so it's not dependent on the auto-reloader nor changing any files.

**Comment by masenf** [comment]
Thank you for reporting this issue. It appears to be related to one of our dependencies, `python-engineio`.

When I pin `python-engineio-4.5.1`, this error message goes away.

**Comment by masenf** [comment]
Seems that the underlying issue has been fixed upstream: https://github.com/miguelgrinberg/python-engineio/issues/327
