### ISSUE TITLE
UnicodeDecodeError when running reflex init

### ISSUE THREAD

**Issue by sertemo** [reflex-dev/reflex#1697]
**Describe the bug**
  File "C:\Users\Usuario\anaconda3\envs\reflex\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Usuario\anaconda3\envs\reflex\lib\site-packages\reflex\utils\prerequisites.py", line 338, in install_node
    processes.show_status("Installing node", process)
  File "C:\Users\Usuario\anaconda3\envs\reflex\lib\site-packages\reflex\utils\processes.py", line 225, in show_status
    for line in stream_logs(message, process):
  File "C:\Users\Usuario\anaconda3\envs\reflex\lib\site-packages\reflex\utils\processes.py", line 190, in stream_logs
    for line in process.stdout:
  File "C:\Users\Usuario\anaconda3\envs\reflex\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 108: invalid start byte**

**To Reproduce**
Got the exception when running 'reflex init', following the steps in the docs

**Specifics (please complete the following information):**
 - Python Version: 3.10 installed using Conda on an virtual environment
 - Reflex Version: 0.2.6
 - OS: Windows 10 Pro 22H2
 - Browser (Optional): Chrome
 
**Additional context**
No more context

**Comment by sertemo** [comment]
I've just tried and yep, I get the same error.

Info: Overriding config value username with env var USERNAME=Usuario
──────────────────────────────────────────────── Initializing Scripts ─────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Usuario\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\reflex.py", line 75, in init
    prerequisites.initialize_frontend_dependencies()
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\utils\prerequisites.py", line 478, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\utils\processes.py", line 165, in run_concurrently
    task.result()
  File "C:\Users\Usuario\anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Usuario\anaconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Usuario\anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\utils\prerequisites.py", line 338, in install_node
    processes.show_status("Installing node", process)
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\utils\processes.py", line 225, in show_status
    for line in stream_logs(message, process):
  File "G:\CURSOS\Python\mini_projects\test_reflex\venv\lib\site-packages\reflex\utils\processes.py", line 190, in stream_logs
    for line in process.stdout:
  File "C:\Users\Usuario\anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 108: invalid start byte

(venv) G:\CURSOS\Python\mini_projects\test_reflex\venv\Scripts>

**Comment by sertemo** [comment]
Same error with poetry:

  File "G:\CURSOS\Python\mini_projects\test_reflex\.venv\Lib\site-packages\reflex\utils\processes.py", line 225, in show_status
    for line in stream_logs(message, process):
  File "G:\CURSOS\Python\mini_projects\test_reflex\.venv\Lib\site-packages\reflex\utils\processes.py", line 190, in stream_logs
    for line in process.stdout:
  File "<frozen codecs>", line 322, in decode
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 108: invalid start byte**

(test-reflex-py3.11) G:\CURSOS\Python\mini_projects\test_reflex>

**Comment by bellooswaldo** [comment]
This error I solved changing in the `Windows settings Region/Time` select `Aditional options of date, time and regional setting` in `Change format of date, time or number` select in eyelash Administrator `Change regional settings of system` and able the checkmark Version beta: Use UTF-8 Unicode

**Comment by sertemo** [comment]
It worked !

Thanks !
