### ISSUE TITLE
Trying to run a simple example from medium and getting a weird Directory error

### ISSUE THREAD

**Issue by rapidarchitect** [reflex-dev/reflex#1793]
Environment: windows 10
Python: 3.10

Error Message:
(venv) D:\py-reflex-gui>python image.py
Info: Overriding config value username with env var USERNAME=mikeh
Info: Overriding config value username with env var USERNAME=mikeh
Info: Overriding config value username with env var USERNAME=mikeh
Info: Overriding config value username with env var USERNAME=mikeh
Info: Overriding config value username with env var USERNAME=mikeh
Info: Overriding config value username with env var USERNAME=mikeh
Compiling:  ---------------------------------------- 100% 2/2 0:00:00
Info: Overriding config value username with env var USERNAME=mikeh
Traceback (most recent call last):
  File "D:\py-reflex-gui\image.py", line 55, in <module>
    app.compile()
  File "D:\py-reflex-gui\venv\lib\site-packages\reflex\app.py", line 634, in compile
    self.get_frontend_packages(all_imports)
  File "D:\py-reflex-gui\venv\lib\site-packages\reflex\app.py", line 544, in get_frontend_packages
    prerequisites.install_frontend_packages(page_imports)
  File "D:\py-reflex-gui\venv\lib\site-packages\reflex\utils\prerequisites.py", line 426, in install_frontend_packages
    process = processes.new_process(
  File "D:\py-reflex-gui\venv\lib\site-packages\reflex\utils\processes.py", line 150, in new_process
    return fn(args, **kwargs)
  File "c:\Users\mikeh\.pyenv\pyenv-win\versions\3.9.13\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\mikeh\.pyenv\pyenv-win\versions\3.9.13\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

Code:

**Comment by richardschoen** [comment]
I just tried with Python 3.9 and same error. 

@rapidarchitect Did you ever resolve this ?

**Comment by masenf** [comment]
Need to run reflex app via `reflex run` in the same directory as `rxconfig.py`. Executing the app module directly wont work.
