### ISSUE TITLE
Reflex init error, UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte

### ISSUE THREAD

**Issue by reyzovw** [reflex-dev/reflex#1795]
**Describe the bug**
When using reflex init error invalid start byte

**To Reproduce**
(venv) PS C:\Users\reyzov_developer\Desktop\reflex-chat-main> reflex init --loglevel debug
Info: Overriding config value username with env var USERNAME=reyzov_developer
Info: Overriding config value username with env var USERNAME=reyzov_developer
────────────────────────────────────────────────────────── System Info ───────────────────────────────────────────────────────────
Debug: Config file: 'C:\\Users\\reyzov_developer\\Desktop\\reflex-chat-main\\venv\\Lib\\site-packages\\reflex\\config.py'
Debug: Config: app_name='' loglevel=<LogLevel.INFO: 'info'> frontend_port=3000 frontend_path='' backend_port=8000 
api_url='http://localhost:8000' deploy_url='http://localhost:3000' backend_host='0.0.0.0' db_url='sqlite:///reflex.db' 
redis_url=None telemetry_enabled=True bun_path='C:\\Users\\reyzov_developer\\AppData\\Local\\reflex\\bun\\bin\\bun' 
cors_allowed_origins=['*'] tailwind=None timeout=120 next_compression=True event_namespace=None frontend_packages=[] 
rxdeploy_url=None username='reyzov_developer'
Warning: The path to the Node binary could not be found. Please ensure that Node is properly installed and added to your system's 
PATH environment variable.
Debug: Running command: [None, '-v']
Debug: [Reflex 0.2.7 with Python 3.11.5 (PATH: C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Scripts\python.exe)]       
Debug: [Node None (Expected: 18.17.0) (PATH:None)]
Debug: [FNM 1.35.1 (Expected: 1.35.1) (PATH: C:\Users\reyzov_developer\AppData\Local\reflex\fnm\fnm.exe)]
Debug: [OS Windows 10.0.22000]
Debug: Using package installer at: None
Debug: Using package executer at: None
───────────────────────────────────────────────── Initializing reflex_chat_main ──────────────────────────────────────────────────
Debug: Skipping bun installation on Windows.
Warning: The path to the Node binary could not be found. Please ensure that Node is properly installed and added to your system's 
PATH environment variable.
Debug: Running command: ['powershell', '-Command', '& "C:\\Users\\reyzov_developer\\AppData\\Local\\reflex\\fnm\\fnm.exe" install 
18.17.0 --fnm-dir "C:\\Users\\reyzov_developer\\AppData\\Local\\reflex\\fnm"']
Debug: Installing node
Traceback (most recent call last):                                                                                                
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\reflex.py", line 75, in init
    prerequisites.initialize_frontend_dependencies()
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\prerequisites.py", line 569, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\processes.py", line 192, in run_concurrently
    with run_concurrently_context(*fns):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\processes.py", line 183, in run_concurrently_context
    task.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\prerequisites.py", line 384, in install_node
    processes.show_status("Installing node", process)
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\processes.py", line 248, in show_status
    for line in stream_logs(message, process):
  File "C:\Users\reyzov_developer\Desktop\reflex-chat-main\venv\Lib\site-packages\reflex\utils\processes.py", line 215, in stream_logs
    for line in process.stdout:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte

**Expected behavior**
The reflex init command must be executed

**Specifics (please complete the following information):**
 - 3.11:
 - latest:
 - Windows 11 64x:

**Comment by fabJunior** [comment]
It might be worth noting that I stumbled upon the same error, though using powershell 5.1 instead of powershell 7 solved the issue on my end.

Consistently, when running `reflex init` in powershell 7 I get the error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 26: invalid start byte` at the `Installing node` step.
But it works fine with powershell 5.1

**Comment by masenf** [comment]
Fixed in #3096
