### ISSUE TITLE
Error reflex init

### ISSUE THREAD

**Issue by RajaSunrise** [reflex-dev/reflex#1854]
**Describe the bug**
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psutil/_pslinux.py", line 285, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/local/lib/python3.11/dist-packages/psutil/_common.py", line 432, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/dist-packages/psutil/_common.py", line 430, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psutil/_pslinux.py", line 268, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psutil/_common.py", line 765, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/stat'
The app directory cannot be named reflex.

![Screenshot_2023-09-22-19-18-29-944_com.termux.png](https://github.com/reflex-dev/reflex/assets/141462335/557b18a3-8d60-444a-bcf5-0da80b6fa30b)

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.2.7
 - OS: kali linux
 - Browser (Optional):

**Comment by Lendemor** [comment]
Hello.
Like the error message say, you can't create an app called reflex, this is a reserved name.
Create a folder with a different name and run `reflex init` inside that folder.

**Comment by RajaSunrise** [comment]
Thank my frend
