### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Dumbliidore** [reflex-dev/reflex#1870]
**Describe the bug**
It's a TypeError while i using reflex run

**Specifics (please complete the following information):**
 - Python Version:  3.11
 - Reflex Version:   0.28
 - OS:  Windows11
 
**Additional context**
```
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 157/157 0:00:15
Traceback (most recent call last):
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\format.py", line 328, in format_prop
    prop = serializers.serialize_dict(prop)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\serializers.py", line 160, in serialize_dict
    fprop = json_dumps(prop_dict)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\format.py", line 576, in json_dumps
    return json.dumps(obj, ensure_ascii=False, default=list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\pyenv-win-3.1.1\pyenv-win\versions\3.11\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "D:\Program Files\pyenv-win-3.1.1\pyenv-win\versions\3.11\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\pyenv-win-3.1.1\pyenv-win\versions\3.11\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: 'function' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Study\rex\.venv\Scripts\reflex.EXE\__main__.py", line 7, in <module>
  File "D:\Study\rex\.venv\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\reflex.py", line 146, in run
    prerequisites.get_app()
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\prerequisites.py", line 114, in get_app
    app = __import__(module, fromlist=(constants.APP_VAR,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\reflex-web\pcweb\pcweb.py", line 122, in <module>
    app.compile()
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\app.py", line 617, in compile
    compile_results = [result.get() for result in compile_results]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\app.py", line 617, in <listcomp>
    compile_results = [result.get() for result in compile_results]
                       ^^^^^^^^^^^^
  File "D:\Program Files\pyenv-win-3.1.1\pyenv-win\versions\3.11\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
  File "D:\Program Files\pyenv-win-3.1.1\pyenv-win\versions\3.11\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\compiler\compiler.py", line 300, in compile_page
    code = _compile_page(component, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\compiler\compiler.py", line 120, in _compile_page
    render=component.render(),
           ^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in render
    children=[child.render() for child in self.children],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in <listcomp>
    children=[child.render() for child in self.children],
              ^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in render
    children=[child.render() for child in self.children],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in <listcomp>
    children=[child.render() for child in self.children],
              ^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in render
    children=[child.render() for child in self.children],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 495, in <listcomp>
    children=[child.render() for child in self.children],
              ^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\el\element.py", line 33, in render
    children=[child.render() for child in self.children],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\el\element.py", line 33, in <listcomp>
    children=[child.render() for child in self.children],
              ^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\component.py", line 497, in render
    props=tag.format_props(),
          ^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\components\tags\tag.py", line 54, in format_props
    return format.format_props(*self.special_props, **self.props)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\format.py", line 354, in format_props
    return [
           ^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\format.py", line 355, in <listcomp>
    f"{name}={format_prop(prop)}"
              ^^^^^^^^^^^^^^^^^
  File "D:\Study\rex\.venv\Lib\site-packages\reflex\utils\format.py", line 336, in format_prop
    raise TypeError(f"Could not format prop: {prop} of type {type(prop)}") from e
TypeError: Could not format prop: {'componentMap': {'h1': <function docheader2 at 0x000001EE71016FC0>, 'h2': <function subheader2 at 0x000001EE71016DE0>, 'a': <function doclink2 at 0x000001EE71017920>, 'p': <function doctext at 0x000001EE71016D40>, 'code': <function <lambda> at 0x000001EE70F59120>}} of type <class 'reflex.style.Style'>
```

**Comment by ElijahAhianyo** [comment]
could you provide the code example to reproduce this error?

**Comment by picklelo** [comment]
Looks like this is using the latest `reflex-web`. This requires the latest `reflex` main branch to run correctly.

**Comment by D-Ayden** [comment]
> Looks like this is using the latest `reflex-web`. This requires the latest `reflex` main branch to run correctly.看起来这是使用最新的 `reflex-web` .这需要最新的 `reflex` 主分支才能正常运行。

Yes, it's the latest reflex-web,

 the version of reflex library is 0.2.8.

**Comment by D-Ayden** [comment]
> this is using the latest `reflex-web`.

**Comment by D-Ayden** [comment]
> tly.

This is using the latest reflex-web.

**Comment by D-Ayden** [comment]
> could you provide the code example to reproduce this error?

This is using the latest reflex-web. I installed all dependent libraries according to the reqirements.txt file, but it was wrong.

**Comment by picklelo** [comment]
This should be resolved now.
