### ISSUE TITLE
Reflex requires unzip to be installed.

### ISSUE THREAD

**Issue by raul-progr** [reflex-dev/reflex#1958]
**Describe the bug**
I was trying to install and set up all the environment in the WSL with VScode, but i can't run the command reflex init, the error code is "Reflex requires unzip to be installed."

**To Reproduce**
I can't list steps to reproduce, i know that i have a proper WSL2 environment working perfectly, the python version that i am using is 3.10.12 and the linux subsystem is ubuntu

This is the console log that im getting after running the command "reflex init"

Log:

Traceback (most recent call last):
  File "/home/rulo/linkbio/venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/reflex/reflex.py", line 76, in init
    prerequisites.initialize_frontend_dependencies()
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/reflex/utils/prerequisites.py", line 606, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/reflex/utils/processes.py", line 192, in run_concurrently
    with run_concurrently_context(*fns):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/reflex/utils/processes.py", line 183, in run_concurrently_context
    task.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rulo/linkbio/venv/lib/python3.10/site-packages/reflex/utils/prerequisites.py", line 436, in install_bun
    raise FileNotFoundError("Reflex requires unzip to be installed.")
FileNotFoundError: Reflex requires unzip to be installed.

 - Python Version: 3.10.12
 - Reflex Version: latest 0.2.9
 - OS: WSL ubuntu

**Comment by raul-progr** [comment]
Wont, fix issue was that the unzip app wasn't installed in the os
