### ISSUE TITLE
How to `stop_propagation` with lambda funtions or callable function references

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#2132]
Hi I'm wondering how to stop the propagation of events with lambda functions and callable function references.

Example code:
```python

from typing import Any, Callable
import reflex as rx

class State(rx.State):
    """The app state."""

    def dummy_func(self):
        rx.console_log("Ran dummy func")

def my_function_wrapper(on_click: Callable[[Any], None]) -> rx.Component:
    return rx.button(
        "Wrapper component",
        on_click=on_click.stop_propagation,
    )

def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.vstack(
            rx.heading("Lambda button"),
            rx.button("Lambda", on_click=(lambda : rx.console_log("")).stop_propagation),
            rx.heading("Wrapper"),
            my_function_wrapper(on_click=State.dummy_func),
        ),
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by jpbaltazar** [comment]
@Lendemor Thank you! Can confirm it definitely works for the lambda case, but what about the function wrapper case? What would be the type of the function to be able to call `.stop_propagation`

**Comment by jpbaltazar** [comment]
@masenf Hi, since you've helped me before on this, any insight for the function case?

**Comment by jpbaltazar** [comment]
The function call does not work, this means that I cannot make custom components that take on_click functionality that won't propagate.

```
Traceback (most recent call last):
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/reflex/reflex.py", line 257, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/reflex/reflex.py", line 188, in _run
    prerequisites.get_app()
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 130, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/vscode-workspace/reflex-stop-propagation-example/reflex_stop_propagation_example/reflex_stop_propagation_example.py", line 31, in <module>
    app.add_page(index)
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/reflex/app.py", line 401, in add_page
    component = self._generate_component(component)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josem/.cache/pypoetry/virtualenvs/reflex-stop-propagation-example-6LglbzMr-py3.11/lib/python3.11/site-packages/reflex/app.py", line 343, in _generate_component
    return component if isinstance(component, Component) else component()
                                                              ^^^^^^^^^^^
  File "/home/josem/vscode-workspace/reflex-stop-propagation-example/reflex_stop_propagation_example/reflex_stop_propagation_example.py", line 22, in index
    rx.button("Lambda", on_click=(lambda : rx.console_log("")).stop_propagation),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'stop_propagation'
```
