### ISSUE TITLE
Using the rx.html component encounters a bug, I must manually refresh the page for it to load properly.

### ISSUE THREAD

**Issue by Brandon-lz** [reflex-dev/reflex#2203]
**Describe the bug**
When I use the rx.html component to implement the camera function, I need to manually refresh the page to use it normally.

**mycode**
I use template sidebar, and define the code in pages/camera.py:
```python
"""The home page of the app."""

from ..templates import template

import reflex as rx

# back_end_host = "http://127.0.0.1:8083"
face_back_end_host = "https://9gtnml-8080.csb.app"

# request to face backend
js_request = f"""

var i=0;


function recogFace(){{

    function send_picture(image) {{

        var canvas = document.createElement('canvas');
        canvas.width = image.width;
        canvas.height = image.height;
        canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);
        var image_base64 = canvas.toDataURL('image/png');
    

        const url = '{face_back_end_host}/img-test';
        const data = {{ img: image_base64 }};

        
        fetch(url, {{
            method: 'POST',
            headers: {{
                'Content-Type': 'application/json'
            }},
            body: JSON.stringify(data)
            }})
            .then(response => response.json())
            .then(data => {{
                // Handle the response data here
                console.log(data);
                if (data['my_result']=='ok'){{
                    recogFace();        // request all the time until correct reesult 
                }} else {{
                    // return;
                    window.location.href = "https://www.google.com";    // rest
                    return
                }}
            }})
            .catch(error => {{
                // Handle any errors that occurred during the request
                console.error(error);
            }}
        );
        
    }}

    console.log(i);
    var video = document.getElementById('videoElement');
    var videoTrack = video.srcObject.getVideoTracks()[0];
    let imageCapture = new ImageCapture(videoTrack);
    imageCapture.grabFrame()
        .then(imageBitmap => {{
     
            console.log(imageBitmap);
            var image = imageBitmap
            i++;
            send_picture(image);
    
        }})
        .catch(error => {{
            console.error('Error grabbing frame:', error);
        }});
}}

recogFace();
"""


@template(route="/camera", title="camera", image="/github.svg")
def camera_page() -> rx.Component:
    """The home page.

    Returns:
        The UI for the home page.
    """

    return rx.box(
        rx.html(
            """
<video id="videoElement0" autoplay></video>
<video id="videoElement1" autoplay></video>

<script>
navigator.mediaDevices.enumerateDevices()
    .then(devices => {
        const videoDevices = devices.filter(device => device.kind === 'videoinput');
        const videoStreams = videoDevices.map(device => {
            return navigator.mediaDevices.getUserMedia({ video: { deviceId: device.deviceId } });
        });
        let numCallbackRuns = 0;
        Promise.all(videoStreams)
            .then(streams => {
                streams.forEach(stream => {
                    // const videoElement = document.createElement('video');
                    const videoElement = document.getElementById(('videoElement'+numCallbackRuns));
                    console.log(videoElement);
                    videoElement.srcObject = stream;  
                    // document.body.appendChild(videoElement);
                    numCallbackRuns++;
                });
            })
            .catch(error => {
                console.error('Error accessing video streams:', error);
            });
    })
    .catch(error => {
        console.error('Error enumerating video devices:', error);
    });

</script>
            """,

            max_width="300px",  
            height="auto",
            transform="scaleX(-1);",  
        ),
        rx.button("take a picture", on_click=lambda: rx.call_script(js_request)),
    )

```

**Expected behavior**
When I click the camera button in sidebar, the page loaded incorrect, and chrome DevTools display the error as fallow:
```
Warning: Received `true` for a non-boolean attribute `ordered`.

If you want to write it to the DOM, pass a string instead: ordered="true" or ordered={value.toString()}.
    at li
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:49:102)
    at ListItem2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-Z47J5YMH.mjs:62:18)
    at li (webpack-internal:///./pages/index.js:643:47)
    at ol
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:49:102)
    at List2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-Z47J5YMH.mjs:26:88)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-Z47J5YMH.mjs:52:11)
    at ol (webpack-internal:///./pages/index.js:629:47)
    at ReactMarkdown (webpack-internal:///./node_modules/react-markdown/lib/react-markdown.js:88:42)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:49:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:49:102)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at ChakraComponent (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-E32MZNBA.mjs:49:102)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chunk-O5CRURSQ.mjs:23:5)
    at HStack
    at Component (webpack-internal:///./pages/index.js:55:68)
    at EventLoopProvider (webpack-internal:///./utils/context.js:65:11)
    at ChakraColorModeProvider (webpack-internal:///./components/reflex/chakra_color_mode_provider.js:19:11)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/chunk-23XYWYLU.mjs:32:11)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/chunk-4DEUOPYU.mjs:28:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:123:50)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/chunk-3ZTTLJBV.mjs:26:11)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/chunk-5PBJXT35.mjs:18:5)
    at ChakraProvider2 (webpack-internal:///./node_modules/@chakra-ui/react/dist/chunk-DGNA6VRZ.mjs:17:5)
    at AppWrap (webpack-internal:///./pages/_app.js:36:11)
    at $ (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:578)
    at y (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:348)
    at MyApp (webpack-internal:///./pages/_app.js:63:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5391)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7787)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:79:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:183:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:397:11)
```

**Specifics (please complete the following information):**
 - Python Version:3.11.6
 - Reflex Version: 0.3.4
 - OS: debian
 - Browser (Optional):chrome/edge

**Comment by masenf** [comment]
The `rx.html` component is not designed to work with scripts. To invoke custom scripts, use `rx.script` and `rx.call_script`: https://reflex.dev/docs/api-reference/browser_javascript/

For more ideas around capturing images and videos with reflex, I'm working on an app for reflex-examples that might be of interest: https://github.com/reflex-dev/reflex-examples/pull/169 https://github.com/reflex-dev/reflex-examples/pull/171/files

**Comment by Brandon-lz** [comment]
> The `rx.html` component is not designed to work with scripts. To invoke custom scripts, use `rx.script` and `rx.call_script`: https://reflex.dev/docs/api-reference/browser_javascript/
> 
> For more ideas around capturing images and videos with reflex, I'm working on an app for reflex-examples that might be of interest: [reflex-dev/reflex-examples#169](https://github.com/reflex-dev/reflex-examples/pull/169) https://github.com/reflex-dev/reflex-examples/pull/171/files

Okay, I understand. Looking forward to the early release of the new features.

**Comment by Brandon-lz** [comment]
> The `rx.html` component is not designed to work with scripts. To invoke custom scripts, use `rx.script` and `rx.call_script`: https://reflex.dev/docs/api-reference/browser_javascript/
> 
> For more ideas around capturing images and videos with reflex, I'm working on an app for reflex-examples that might be of interest: [reflex-dev/reflex-examples#169](https://github.com/reflex-dev/reflex-examples/pull/169) https://github.com/reflex-dev/reflex-examples/pull/171/files

Thank you for your answer, and looking forward to the release of new features.
