### ISSUE TITLE
[REF-1896] I found an error that when using the "reflex init" command gives me this error:

### ISSUE THREAD

**Issue by CrisBelDev** [reflex-dev/reflex#2305]
I found an error that when using the "reflex init" command gives me this error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Scripts\reflex.exe\__main__.py", line 7, in <module>    
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\typer\main.py", line 328, in __call__ 
    raise e
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\typer\main.py", line 311, in __call__ 
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\typer\core.py", line 778, in main     
    return _main(
           ^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\typer\core.py", line 216, in _main    
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\reflex.py", line 123, in init
    _init(name, template, loglevel)
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\reflex.py", line 84, in _init
    prerequisites.initialize_frontend_dependencies()
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\prerequisites.py", line 751, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\processes.py", line 199, in run_concurrently
    with run_concurrently_context(*fns):
  File "C:\Users\CHICHO\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\processes.py", line 186, in run_concurrently_context
    task.result()
  File "C:\Users\CHICHO\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\CHICHO\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\prerequisites.py", line 557, in install_node
    processes.show_status("Installing node", process)
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\processes.py", line 256, in show_status
    for line in stream_logs(message, process):
  File "C:\Users\CHICHO\Proyectos\pythonWeb\envpy\Lib\site-packages\reflex\utils\processes.py", line 223, in stream_logs
    for line in process.stdout:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 17: invalid start byte
```

(I need help please)

<sub>[REF-1896](https://linear.app/reflex-dev/issue/REF-1896/i-found-an-error-that-when-using-the-reflex-init-command-gives-me-this)</sub>

**Comment by Alek99** [comment]
Please provide more details such as reflex version, python version etc. As suggested in the issue template.

**Comment by DANIElPEZ** [comment]
I use:

Python: 3.11.7
Reflex: 0.3.9

and i solve it changing the function stream_logs

source code of function:

`
import sys

def stream_logs(message, process):
    try:
        # Read and decode each line from the process's stdout
        for line in process.stdout:
            if isinstance(line, str):
                decoded_line = line
            else:
                # Decode byte-like objects
                decoded_line = line.decode('utf-8', errors='replace')  # Replace invalid bytes
            sys.stdout.write(decoded_line)
            sys.stdout.flush()
    except UnicodeDecodeError as e:
        print(f"Error decoding line: {e}")
        # Handle the error gracefully, e.g., by printing a message and skipping the line
    except Exception as ex:
        print(f"Error streaming logs: {ex}")
        # Handle other exceptions as needed

    # Return an empty iterable in case of success or error
    return iter([])
`

**Comment by picklelo** [comment]
@DANIElPEZ nice catch - could you put a PR up with your change, we can review it and make sure it works for future users

**Comment by DANIElPEZ** [comment]
I'm sorry, what is PR?

**Comment by DANIElPEZ** [comment]
the readme it's when you have install reflex in venv, so have follow the steps in readme, if you read readme, 
you will need to modify stream logs function

the page: https://github.com/DANIElPEZ/DaniDev-software

**Comment by adhami3310** [comment]
if anyone else hits this, please feel free to open a new ticket with a bit more documentation and repro code
