### ISSUE TITLE
LocalHost Immediately Disconnects After Saving the .py File

### ISSUE THREAD

**Issue by Volteau85** [reflex-dev/reflex#2307]
**Describe the bug**
When running Reflex, the code appears at it should, at first. Any changes I make and save are not hot reloaded (meaning I see no change in the localhost) and the localhost disconnects me from the server. I monitored the situation with XAMPP, and the moment I save the changes it goes from new Port (or Active Socket) into Old Socket and then disappears, which I take it to mean it disconnects. I've tried disabling the firewall, but the problem persists.

**To Reproduce**
 - Code/Link to Repo:

While I don't believe the code itself is the culprit, here are the two files I have working in tandem for now (literally just started working on it). Because of the localhost issues, it seems that the image won't load as well, though the MENU dropdown does. 

**ReflexProj.py**

import reflex as rx
from .components.navbar import navbar

def index():
    return rx.container(
        navbar()
    )

def about():
    return rx.text('This is an about page.')

app = rx.App()
app.add_page(index)
app.add_page(about)
app.compile()

**navbar.py**

import reflex as rx

def navbar():
    return rx.flex(
        rx.box(
            rx.image(src='/AvandraLogo.png',
            )
        ),
        rx.box(
            rx.menu(
                rx.menu_button('MENU'),
                rx.menu_list(
                    rx.menu_item('About'),
                    rx.menu_item('News')
                )
            )
        ),
        justify_content = 'space-between'
    )

**Expected behavior**
I expected to see all my changes hot reloaded to the localhost3000 page. 

**Screenshots**
Standard "localhost refused connection" screen.

**Specifics (please complete the following information):**
 - Python Version: 3.12.0
 - Reflex Version: 0.3.4
 - OS: Win10
 - Browser (Optional): Tried it on opera, Chrome, and even Edge

Other Important Info:

Even though the process disappears rom XAMPP, sometimes it says there is still something occupying port 3000, even if the connection is refused in the browser.

**Comment by Volteau85** [comment]
**Update**

Ran it through Git Bash (after WSL failed to update and would just close), and got this error:

ERROR:    Traceback (most recent call last):
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 89, in startup
    await self.lifespan.startup()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\lifespan\on.py", line 54, in startup
    await self.startup_event.wait()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 89, in startup
    await self.lifespan.startup()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\lifespan\on.py", line 54, in startup
    await self.startup_event.wait()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\survi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
Compiling:  ---------------------------------------- 100% 3/3 0:00:00

**Comment by masenf** [comment]
thanks for reporting. will track this is #2335
