### ISSUE TITLE
relfex init fail

### ISSUE THREAD

**Issue by EzequielQuintana** [reflex-dev/reflex#2449]
**Describe the bug**
Falla cuando hago reflex init
**To Reproduce**
 - Code/Link to Repo:
```reflex init
─────────────────────────────────────────────────────────────────────────────────────── Initializing link_bio2 ───────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/niko/Documentos/python/link_bio2/venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/reflex.py", line 123, in init
    _init(name, template, loglevel)
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/reflex.py", line 94, in _init
    prerequisites.initialize_frontend_dependencies()
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 834, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/utils/processes.py", line 199, in run_concurrently
    with run_concurrently_context(*fns):
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/utils/processes.py", line 186, in run_concurrently_context
    task.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 606, in install_bun
    if os.path.exists(get_config().bun_path) and get_bun_version() == version.parse(
                                                 ^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 107, in get_bun_version
    return version.parse(result.stdout)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/niko/Documentos/python/link_bio2/venv/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```
**Expected behavior**
que se ejecute correctamente

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: reflex             0.3.9
reflex-hosting-cli 0.1.6

 - OS:  DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.3
DISTRIB_CODENAME=una
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

 - Browser (Optional):
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
your logs are missing the `system info` aspect which shows before the initialization step.
Should look something like this:
`───────────────────────────────── System Info ──────────────────────────────────`

can you re-run `reflex init --loglevel debug` and add that?

**Comment by masenf** [comment]
If `reflex init` crashes before its able to output system info, can you post the bun version by running it directly?

```
.local/share/reflex/bun/bin/bun --version
```

**Comment by EzequielQuintana** [comment]
.local/share/reflex/bun/bin/bun --version
Instrucción ilegal (`core' generado)

**Comment by masenf** [comment]
@EzequielQuintana okay i think you're hitting https://github.com/oven-sh/bun/issues/67, which shows up on older machines.

To confirm this theory, download the "baseline" build of bun, and extract it to `~/.local/share/reflex/bun/bin/bun`, then see if you can get the version.

https://github.com/oven-sh/bun/releases/download/bun-v1.0.25/bun-linux-x64-baseline.zip

**Comment by EzequielQuintana** [comment]
Same error

sudo .local/share/reflex/bun/bin/bun --version
Instrucción ilegal

**Comment by iddrisumohamme1** [comment]
Same error message                                                                                                                                          PS C:\Users\acer i3\my_app_name> reflex init
reflex : The term 'reflex' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name,  
or if a path was included, verify that the path is correct and try again.    
At line:1 char:1
+ reflex init
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (reflex:String) [], CommandNo  
   tFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by picklelo** [comment]
@iddrisumohamme1 Are you using a virtual env as recommended in the docs?

**Comment by iddrisumohamme1** [comment]
yes

**Comment by ElijahAhianyo** [comment]
> Same error message PS C:\Users\acer i3\my_app_name> reflex init reflex : The term 'reflex' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> 
> * reflex init
> * ```
>     + CategoryInfo          : ObjectNotFound: (reflex:String) [], CommandNo  
>    tFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>                                                                                                                                                                 
>   ```

Can you confirm if this is still an issue?
