### ISSUE TITLE
`pipenv install reflex` just hangs

### ISSUE THREAD

**Issue by spierepf** [reflex-dev/reflex#2560]
```
$ uname -a
Linux fedora 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux

$ python --version
Python 3.11.7

$ pipenv --version
pipenv, version 2022.10.25

$ pipenv install reflex
Installing reflex...
⠦ Installing reflex...
```

And it will sit and spin forever.

**Comment by spierepf** [comment]
It finally died:

```
INFO: pip is looking at multiple versions of psutil to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of platformdirs to determine which version is compatible with other requirements. This could take a while.
Collecting platformdirs<4.0.0,>=3.10.0
  Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
INFO: pip is looking at multiple versions of pipdeptree to determine which version is compatible with other requirements. This could take a while.
Collecting pipdeptree<3.0.0,>=2.13.0
  Downloading pipdeptree-2.13.1-py3-none-any.whl (26 kB)
  Downloading pipdeptree-2.13.0-py3-none-any.whl (26 kB)
INFO: pip is looking at multiple versions of platformdirs to determine which version is compatible with other requirements. This could take a while.
ERROR: Exception:
Traceback (most recent call last):
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/.local/share/virtualenvs/reflexSandbox-FcOor_wf/lib64/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

**Comment by ChristophGreger** [comment]
Following command fixed similar issue for me (just updating pip): 
`pip install --upgrade pip `
