### ISSUE TITLE
[REF-2049] rx.debounce_input does not work raising a type error 

### ISSUE THREAD

**Issue by pedrojfernandez** [reflex-dev/reflex#2683]
**Describe the bug**
The error appears when we use rx.debounce_input to envelope a rx.input linked with a state variable.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Scripts\reflex.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\typer\core.py", line 778, in main
    return _main(
           ^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\typer\core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\reflex.py", line 258, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\reflex.py", line 189, in _run
    prerequisites.get_compiled_app()
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\utils\prerequisites.py", line 186, in get_compiled_app
    app_module = get_app(reload=reload)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\utils\prerequisites.py", line 163, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\Prueba\Prueba.py", line 43, in <module>
    app.add_page(index)
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\app.py", line 428, in add_page
    component = self._generate_component(component)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\app.py", line 379, in _generate_component
    raise e
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\app.py", line 368, in _generate_component
    return component if isinstance(component, Component) else component()
                                                              ^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\Prueba\Prueba\Prueba.py", line 22, in index
    rx.debounce_input(
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\components\core\debounce.py", line 98, in create
    if not props.get("input_ref") and child_ref:
  File "C:\Users\xxxxxx\Documents\Prueba\.venv\Lib\site-packages\reflex\vars.py", line 539, in __bool__
    raise TypeError(
TypeError: Cannot convert Var 'ref_state_variable' to bool for use with `if`, `and`, `or`, and `not`. Instead use `rx.cond` and bitwise operators `&` (and), `|` (or), `~
` (invert).
```

**To Reproduce**

-Create a new project.
-In state define a new state var
-Use this code in the main file of the project:

```
from rxconfig import config

import reflex as rx

docs_url = "https://reflex.dev/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"


class State(rx.State):
    """The app state."""
    state_variable : str = ""


def index() -> rx.Component:
    return rx.center(
        rx.vstack(
            rx.heading("Reproducing debounce_input error", size="9"),
            rx.vstack(
                rx.text ("State variable"),
                rx.debounce_input(
                    rx.chakra.input( 
                         
                        id="state variable" , 
                        value=State.state_variable, 
                        on_change=State.set_state_variable
                    ),
                    debounce_timeout=1000
                ),
            width="28%"),
            rx.text(State.state_variable),
            
            align="center",
            spacing="7",
            font_size="2em",
        ),
        height="100vh",
    )


app = rx.App()
app.add_page(index)
```

**Expected behavior**
Be able to use debounce_input. Now is impossible.

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.4.1
 - OS: Windows 10
 - Browser (Optional): Chrome
 

<sub>[REF-2049](https://linear.app/reflex-dev/issue/REF-2049/rxdebounce-input-does-not-work-raising-a-type-error)</sub>

**Comment by picklelo** [comment]
Thanks for reporting, we will fix this

**Comment by ElijahAhianyo** [comment]
@pedrojfernandez,  Will fix this, however, this is an interesting case, the input component is under the hood a debounce input, so there's no need to wrap it in an `rx.debounce_input`, specifying a `debounce_timeout` in the `input` component should suffice:

```python
rx.chakra.input( 
     id="state variable" , 
     value=State.state_variable, 
     on_change=State.set_state_variable,
     debounce_timeout=1000
),
                    
```
