### ISSUE TITLE
data_editor Component Bug(On WSL) :: AttributeError: module 'reflex' has no attribute 'data_editor'

### ISSUE THREAD

**Issue by wlsfla** [reflex-dev/reflex#2913]
**Describe the bug**
I am aiming to implement an editble data table

**To Reproduce**
I implemented `test` method what display editble data table using rx.data_editor method
```
"""Welcome to Reflex! This file outlines the steps to create a basic app."""
from rxconfig import config

import reflex as rx
from typing import Any

docs_url = "https://reflex.dev/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"


class State(rx.State):
    """The app state."""

    pass

def test() -> rx.Component:
    columns: list[dict[str, str]] = [
        {
            "title": "Code",
            "type": "str",
        },
        {
            "title": "Value",
            "type": "int",
        },
        {
            "title": "Activated",
            "type": "bool",
        },
    ]

    data: list[list[Any]] = [
        ["A", 1, True],
        ["B", 2, False],
        ["C", 3, False],
        ["D", 4, True],
        ["E", 5, True],
        ["F", 6, False],
    ]

    return rx.container(
        rx.data_editor(
            columns=columns,
            data=data,
        )
    )


# Add state and page to the app.
app = rx.App()
app.add_page(test, route="/")
app.compile()

```

**Expected behavior**
I Expected that displaying `data editor` Component
but, I saw Exception Message
`AttributeError: module 'reflex' has no attribute 'data_editor'`

Is the `data_editor` Component operating normally?

**Exception Message**
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/reflex/reflex.py", line 147, in run
    prerequisites.get_app()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 114, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkk/git/test_reflex/test_reflex/test_reflex.py", line 52, in <module>
    app.add_page(test, route="/")
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/reflex/app.py", line 385, in add_page
    component = self._generate_component(component)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/reflex/app.py", line 328, in _generate_component
    return component if isinstance(component, Component) else component()
                                                              ^^^^^^^^^^^
  File "/home/kkk/git/test_reflex/test_reflex/test_reflex.py", line 43, in test
    rx.data_editor(
    ^^^^^^^^^^^^^^
AttributeError: module 'reflex' has no attribute 'data_editor'
```

**Enviroment**
 - Python Version: 3.11.8(on Conda)
 - Reflex Version: 0.4.5
 - OS: ubuntu(in WSL)
 - Browser (Optional): chrome

**Comment by picklelo** [comment]
In your code you're using `rx.data_table`, where are you calling `rx.data_editor`? It should be available if you're on the latest reflex (which it looks like you are)

**Comment by wlsfla** [comment]
Thx for your comment!
I modified my code, just typing mistake in github editor.(`rx.data_table` -> `rx.data_editor`)
but, still, problems continue to arise.

I already used it LTS Reflex Version.(0.4.5)

**Comment by picklelo** [comment]
This code seems to be working for me on my Mac, I wonder if it's a Windows-specific issue. 

@ElijahAhianyo could you try this out on your machine?

**Comment by wlsfla** [comment]
WTH
I tried my Windows machine, and it is work.
It's seems to be WSL-Specific issue.

**Comment by ElijahAhianyo** [comment]
@wlsfla I'm not able to reproduce this in my WSL ubuntu on windows. Also tried running with your python version(3.11.8) in a conda environment, but that seems to work fine for me, which is weird you're experiencing.

Can you try using a traditional virtualenv in your root dir (`python3 -m venv .venv`) and see if issue still persists?

**Comment by wlsfla** [comment]
@ElijahAhianyo 

I tried it also in other enviroment(in same machine), However, the results remained unchanged.
I tried to reproduce this case in other machine(20.04). However, it was not able to reproduce, couldn't find anything wrong.
There was only a problem with the machine.
Finally I reinstall WSL(22.04) and Everything is back to normal.

what was that?
Thank you for your interest in this case

**Comment by wlsfla** [comment]
@ElijahAhianyo 

There was one feature, In the machine that was in problem, `app.compile()` existed
however, other machine was not existed that Line.

**Comment by picklelo** [comment]
@wlsfla that line shouldn't have any affect anymore, but maybe try to delete it and feel free to reopen this issue if you see this again.
