### ISSUE TITLE
reflex init ERROR

### ISSUE THREAD

**Issue by gioboto** [reflex-dev/reflex#2929]
**Describe the bug**
After installing reflex I try to run reflex init and I get this error :

/.venv/lib/python3.11/site-packages/packaging/version.py", line 200, in init
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''

**To Reproduce**
mkdir test
cd test
python3 -m venv .venv
source .venv/bin/activate
pip install reflex
reflex init

**Expected behavior**

Get started with a template:
blank (https://blank-template.reflex.run) - A minimal template.
sidebar (https://sidebar-template.reflex.run) - A template with a sidebar to navigate pages.

Which template would you like to use? [blank/sidebar] (blank):
[11:44:12] Initializing the app directory.                                                             console.py:85
Traceback (most recent call last):
  File "/home/usuariopy/python/test/.venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 685, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/reflex.py", line 135, in init
    _init(name, template, loglevel)
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/reflex.py", line 103, in _init
    prerequisites.initialize_frontend_dependencies()
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 955, in initialize_frontend_dependencies
    processes.run_concurrently(install_node, install_bun)
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/processes.py", line 217, in run_concurrently
    with run_concurrently_context(*fns):
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/processes.py", line 204, in run_concurrently_context
    task.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 681, in install_bun
    if os.path.exists(get_config().bun_path) and get_bun_version() == version.parse(
                                                 ^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 141, in get_bun_version
    return version.parse(result.stdout)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''

**Specifics (please complete the following information):**
 - Python Version: 3.11.2
 - Reflex Version: 0.4.5
 - OS: Debian 12 (new instalation and updated)
 - pip3 : 23.0.1

 
**Additional context**
OS was just installed and updated

**Comment by gioboto** [comment]
reflex init --loglevel debug

(.venv) usuariopy@debianjrmb:~/python/test$ reflex init --loglevel debug
───────────────────────────────────────────────────────────────────────────── System Info ──────────────────────────────────────────────────────────────────────────────
Debug: Config file: '/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/config.py'
Debug: Config: app_name='test' loglevel=<LogLevel.INFO: 'info'> frontend_port=3000 frontend_path='' backend_port=8000 api_url='http://localhost:8000'
deploy_url='http://localhost:3000' backend_host='0.0.0.0' db_url='sqlite:///reflex.db' redis_url=None telemetry_enabled=True
bun_path='/home/usuariopy/.local/share/reflex/bun/bin/bun' cors_allowed_origins=['*'] tailwind={} timeout=120 next_compression=True event_namespace=None
frontend_packages=[] cp_backend_url='https://rxcp-prod-control-plane.fly.dev' cp_web_url='https://control-plane.reflex.run'
gunicorn_worker_class='uvicorn.workers.UvicornH11Worker'
Debug: Running command: ['/home/usuariopy/.local/share/reflex/fnm/node-versions/v18.17.0/installation/bin/node', '-v']
Debug: Running command: ['/home/usuariopy/.local/share/reflex/fnm/fnm', '--version']
Debug: Running command: ['/home/usuariopy/.local/share/reflex/bun/bin/bun', '-v']
Traceback (most recent call last):
  File "/home/usuariopy/python/test/.venv/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/core.py", line 783, in main
    return _main(
           ^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/typer/main.py", line 685, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/reflex.py", line 135, in init
    _init(name, template, loglevel)
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/reflex.py", line 76, in _init
    exec.output_system_info()
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/exec.py", line 262, in output_system_info
    f"[Bun {prerequisites.get_bun_version()} (Expected: {constants.Bun.VERSION}) (PATH: {config.bun_path})]",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 141, in get_bun_version
    return version.parse(result.stdout)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/usuariopy/python/test/.venv/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
(.venv) usuariopy@debianjrmb:~/python/test$
