### ISSUE TITLE
Broken polymorphism: rx.icon() doesn't work with value from rx.Base field

### ISSUE THREAD

**Issue by a0s** [reflex-dev/reflex#3010]
**Describe the bug**

I created this ticket as a result of [this conversation](https://github.com/orgs/reflex-dev/discussions/3000). The inability to work with data from an rx.Base'd instance field breaks the idea of polymorphism and leads to ugly and inefficient code.

**To Reproduce**
```python
import reflex as rx


class BaseFile(rx.Base):
    name: str
    icon: str

class FileA(BaseFile):
    icon: str = "file-video"

class FileB(BaseFile):
    icon: str = "file-audio"

class FileState(rx.State):
    files: list[BaseFile] = [
        FileA(name="file1"),
        FileB(name="file2")
    ]


def index() -> rx.Component:
    return rx.foreach(
        FileState.files,
        lambda file, index: rx.box(
            rx.icon(file.icon),
            rx.text(file.name),
            # additional: how to get file's class here for e.g. file.class == FileB ?
        )
    )


app = rx.App()
app.add_page(index)
```

The error:
```
Traceback (most recent call last):
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/bin/reflex", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/typer/core.py", line 723, in main
    return _main(
           ^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/typer/main.py", line 688, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/reflex.py", line 262, in run
    _run(env, frontend, backend, frontend_port, backend_port, backend_host, loglevel)
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/reflex.py", line 193, in _run
    prerequisites.get_compiled_app()
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/utils/prerequisites.py", line 228, in get_compiled_app
    app_module = get_app(reload=reload)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/utils/prerequisites.py", line 205, in get_app
    app = __import__(module, fromlist=(constants.CompileVars.APP,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/reflex_playground/reflex_playground.py", line 32, in <module>
    app.add_page(index)
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/app.py", line 458, in add_page
    component = self._generate_component(component)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/app.py", line 398, in _generate_component
    return component if isinstance(component, Component) else component()
                                                              ^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/reflex_playground/reflex_playground.py", line 22, in index
    return rx.foreach(
           ^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/components/core/foreach.py", line 64, in create
    component._render(props=dict(index_var_name="i")).render_component()
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/components/tags/iter_tag.py", line 120, in render_component
    component = self.render_fn(arg, index)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/reflex_playground/reflex_playground.py", line 25, in <lambda>
    rx.icon(file.icon),
    ^^^^^^^^^^^^^^^^^^
  File "/Users/a0s/my/reflex-playground/.direnv/python-3.12/lib/python3.12/site-packages/reflex/components/lucide/icon.py", line 57, in create
    raise AttributeError(
AttributeError: Passing multiple children to Icon component is not allowed: remove positional arguments () to fix
```

**Expected behavior**

rx.icon() should be able to use value from `file.icon` as tag

**Specifics:**
 - Python Version: 3.12
 - Reflex Version: 0.4.6
 - OS: MacOS
 - Browser (Optional): Brave
 
**Additional context**

Additional question: How to get the class of `file` instance inside foreach? `file._var_type` always returns `bla.bla.bla.BaseFile`. 
The inability to get the name of the class (and, for example, call the Fragment function (that returns rx.Component) from it) leads to ineffective crutches such as manual text tags with the name of the class inside the instance.

**Comment by Lendemor** [comment]
Behind the scene, `rx.icon` is not just one component that handle icon, but rather each icon as it's own component (we're using the icons of `Lucide.dev`, but it was the same behaviour when we used `radix-icons` or `chakra-icons`)
What is means is that the tag passed to `rx.icon` is used during compilation to determine which icon to import + render, and at that moment any Var will not be initialized with a value, so it fails.

If we want to make this work, we would have to somehow import all the icons during compilation, which would have horrendous impact on performance.

If you have a specific subset of icons you want to use dynamically, define an `rx.match` with them:

```python

def dynamic_icon(icon_name):
    return rx.match(
        icon_name,
        ("plus", rx.icon("plus")),
        ("minus", rx.icon("minus")),
        ("equal", rx.icon("equal")),
    )
```

**Comment by picklelo** [comment]
We've added docs for this on the icon page, will be reflected on the website soon: https://github.com/reflex-dev/reflex-web/pull/594
