### ISSUE TITLE
Can't run the basic reflex app on the 'arm64' packages of my M1 chip mac

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#3362]
### Discussed in https://github.com/orgs/reflex-dev/discussions/3361

<div type='discussions-op-text'>

<sup>Originally posted by **aditya-arolkar-swe** May 21, 2024</sup>
Did anybody else see this issue while trying to run reflex on their M1+ mac? Looks like it wants `charset_normalizer` in the x86_64 version. Tried to pip uninstall and install charset_normalizer with and without the default binaries and that didn't fix it. 

```
(venv) adityaarolkar@Aditya-Arolkar-MacBook-Pro my_reflex_project % reflex init --template reflex
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/reflex", line 5, in <module>
    from reflex.reflex import cli
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/reflex/reflex.py", line 14, in <module>
    from reflex_cli.utils import dependency
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/reflex_cli/utils/dependency.py", line 11, in <module>
    import charset_normalizer
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

```</div>

**Comment by adhami3310** [comment]
we got rid of charset normalizer
