### ISSUE TITLE
Chaining event with mutable parameter fails

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#4011]
**Describe the bug**
Calling `dataclass.asdict(d)` where `d` contains a value which is a `MutableProxy`, it raises exception.

```
Task exception was never retrieved
future: <Task finished name='Task-47' coro=<AsyncServer._handle_event_internal() done, defined at /Users/masen/code/reflex-dev/VENV-dev311/lib/python3.11/site-packages/socketio/async_server.py:608> exception=TypeError("MutableProxy.__init__() missing 2 required positional arguments: 'state' and 'field_name'")>
Traceback (most recent call last):
  File "/Users/masen/code/reflex-dev/VENV-dev311/lib/python3.11/site-packages/socketio/async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/reflex-dev/VENV-dev311/lib/python3.11/site-packages/socketio/async_server.py", line 646, in _trigger_event
    return await handler.trigger_event(event, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/reflex-dev/VENV-dev311/lib/python3.11/site-packages/socketio/async_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/masen/code/reflex-dev/reflex/reflex/app.py", line 1562, in on_event
    await self.emit_update(update=update, sid=sid)
  File "/Users/masen/code/reflex-dev/reflex/reflex/app.py", line 1525, in emit_update
    self.emit(str(constants.SocketEvent.EVENT), update.json(), to=sid)
                                                ^^^^^^^^^^^^^
  File "/Users/masen/code/reflex-dev/reflex/reflex/state.py", line 2461, in json
    return format.json_dumps(dataclasses.asdict(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1319, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1319, in <genexpr>
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1322, in <genexpr>
    _asdict_inner(v, dict_factory))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1319, in _asdict_inner
    return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MutableProxy.__init__() missing 2 required positional arguments: 'state' and 'field_name'
```

**To Reproduce**
```python
import reflex as rx


class State(rx.State):
    m: list[str] = ["Hello", "World"]

    def ev1(self):
        return State.ev2(self.m)
    
    def ev2(self, msg):
        print(msg)


def index() -> rx.Component:
    return rx.text("hi mom 👋")


app = rx.App()
app.add_page(index, on_load=State.ev1)
```

**Expected behavior**
It should serialize the wrapped list and create the EventSpec with that.

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.6.0
 - OS: macOS 14.5
 
**Additional context**
Found while upgrading flexgen to 0.6.0

Needs a test case.

**Comment by masenf** [comment]
fixed by https://github.com/reflex-dev/reflex/pull/3979
