### ISSUE TITLE
Error when automatic recompile or stop app with some Python modules

### ISSUE THREAD

**Issue by JCTrapero** [reflex-dev/reflex#4077]
Hi,
congratulations for a nice job.

When automatic recompile (because some change on files) or stop app (<Ctrl + C>), we obtain this:

WARNING:  StatReload detected changes in 'PythonWeb_UD02\pages\index.py'. Reloading...
Exception in callback LifespanMixin._run_lifespan_tasks.<locals>.<lambda>(<Task cancell...\compat.py:7>>) at c:\Users\juanc\PythonProjects\PythonWeb_UD02\.venv\Lib\site-packages\reflex\app_mixins\lifespan.py:44
handle: <Handle LifespanMixin._run_lifespan_tasks.<locals>.<lambda>(<Task cancell...\compat.py:7>>) at c:\Users\juanc\PythonProjects\PythonWeb_UD02\.venv\Lib\site-packages\reflex\app_mixins\lifespan.py:44>
Traceback (most recent call last):
  File "C:\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\juanc\PythonProjects\PythonWeb_UD02\.venv\Lib\site-packages\reflex\app_mixins\lifespan.py", line 44, in <lambda>
    task_.add_done_callback(lambda t: t.result())
                                      ^^^^^^^^^^
  File "c:\Users\juanc\PythonProjects\PythonWeb_UD02\.venv\Lib\site-packages\reflex\utils\compat.py", line 25, in windows_hot_reload_lifespan_hack
    await asyncio.sleep(0.5)
  File "C:\Python\Python312\Lib\asyncio\tasks.py", line 665, in sleep
    return await future

I'm using:
Windows 11
Reflex 0.6.1
Uvicorn Server
Python 3.12.6

Can you help me?
Best regards!

**Comment by masenf** [comment]
Fixed by #4083
