### ISSUE TITLE
error: CERT_HAS_EXPIRED when building production-one-port docker image on Windows

### ISSUE THREAD

**Issue by borolepratik** [reflex-dev/reflex#4567]
**Describe the bug**
Unable to build production-one-port docker image, seeing error: CERT_HAS_EXPIRED for https://github.com/reflex-dev/reflex/blob/main/docker-example/production-one-port/Dockerfile#L30

 - Python Version: 3.13.1
 - Reflex Version: 0.6.7
 - OS: Windows 11
 
**Additional context**
```
ERROR [builder 10/12] RUN if [ -f .web/bun.lockb ]; then cd .web && ~/.local/share/reflex/bun/bin/bun install --frozen-lockfile; fi                                            9.1s 
------
 > [builder 10/12] RUN if [ -f .web/bun.lockb ]; then cd .web && ~/.local/share/reflex/bun/bin/bun install --frozen-lockfile; fi:
0.305 bun install v1.1.29 (6d43b366)
0.307 Resolving dependencies
0.643 Resolved, downloaded and extracted [2]
8.776 error: CERT_HAS_EXPIRED downloading tarball to-regex-range@5.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball detect-node-es@1.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball streamsearch@1.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball lodash.merge@4.6.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball source-map@0.5.7
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball ts-interface-checker@0.1.13
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball loose-envify@1.4.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-extglob@2.1.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball find-root@1.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball react-is@16.13.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball didyoumean@1.2.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball read-cache@1.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball import-fresh@3.3.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.stat@2.0.5
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball lodash.isplainobject@4.0.6
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball string-width@4.2.3
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball which@2.0.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball strip-ansi@6.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball babel-plugin-macros@3.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.walk@1.2.8
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball run-parallel@1.2.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball path-parse@1.0.7
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball asynckit@0.4.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball escape-string-regexp@4.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball combined-stream@1.0.8
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball util-deprecate@1.0.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball delayed-stream@1.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball glob-parent@6.0.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball postcss-value-parser@4.2.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball pify@2.3.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball thenify-all@1.6.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball brace-expansion@2.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball ms@2.1.3
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball cssesc@3.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball lines-and-columns@1.2.4
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball commander@4.1.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball normalize-range@0.1.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball js-tokens@4.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball get-nonce@1.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball mz@2.7.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-binary-path@2.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball path-key@3.1.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball proxy-from-env@1.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball camelcase-css@2.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball normalize-path@3.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball globals@11.12.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball shebang-command@2.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball hoist-non-react-statics@3.3.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball parse-json@5.2.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball path-type@4.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball lodash.castarray@4.4.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball any-promise@1.3.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball @alloc/quick-lru@5.2.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball object-assign@4.1.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.scandir@2.1.5
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball dlv@1.1.3
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-glob@4.0.3
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball readdirp@3.6.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball merge2@1.4.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball wrap-ansi@7.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball reusify@1.0.4
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball balanced-match@1.0.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball resolve-from@4.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball thenify@3.3.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball queue-microtask@1.2.3
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball error-ex@1.3.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-number@7.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball json-parse-even-better-errors@2.3.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball shebang-regex@3.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball parent-module@1.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball isexe@2.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball eastasianwidth@0.2.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball emoji-regex@9.2.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-fullwidth-code-point@3.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball is-arrayish@0.2.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball callsites@3.1.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball color-convert@2.0.1
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball glob-parent@5.1.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball color-name@1.1.4
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball yaml@1.10.2
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball ansi-styles@4.3.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball emoji-regex@8.0.0
8.776
8.776 error: CERT_HAS_EXPIRED downloading tarball ansi-regex@5.0.1
------

 1 warning found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 59)
Dockerfile:30
--------------------
  28 |     # Install pre-cached frontend dependencies (if exist)
  29 |     COPY *.web/bun.lockb *.web/package.json .web/
  30 | >>> RUN if [ -f .web/bun.lockb ]; then cd .web && ~/.local/share/reflex/bun/bin/bun install --frozen-lockfile; fi
  31 |
  32 |     # Copy local context to `/app` inside container (see .dockerignore)
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ -f .web/bun.lockb ]; then cd .web && ~/.local/share/reflex/bun/bin/bun install --frozen-lockfile; fi" did not complete successfully: exit code: 1
```

**Comment by larsblumberg** [comment]
Temporary workaround, only suggested for local development:

Add this line to your `Dockerfile`, before the `bun install` RUN command:

```Dockerfile
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by adhami3310** [comment]
one thing you might try is using
```
ENV REFLEX_USE_NPM=1
```
and replace the bun commands with npm. *maybe* it's a bun issue

**Comment by borolepratik** [comment]
this issue is now seen in macos running reflex 0.7.4 in docker with `REFLEX_USE_GRANIAN` set to 1.

```
 => [frontend 7/8] RUN reflex init                                                                                                                                                                                                                             10.4s 
 => ERROR [frontend 8/8] RUN reflex export --frontend-only --no-zip                                                                                                                                                                                            22.8s 
------                                                                                                                                                                                                                                                               
 > [frontend 8/8] RUN reflex export --frontend-only --no-zip:                                                                                                                                                                                                        
0.764 ────────────── Compiling production app and preparing for export. ──────────────                                                                                                                                                                               
1.756 [14:50:24] Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 16/16 0:00:00                                                                                                                                                                               
22.08 Installing base frontend packages failed with exit code 1                                                                                                                                                                                                      
22.08 bun install v1.2.4 (fd9a5ea6)                                                                                                                                                                                                                                  
22.08 Resolving dependencies
22.08 Resolved, downloaded and extracted [900]
22.08 error: CERT_HAS_EXPIRED downloading tarball read-cache@1.0.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball asynckit@0.4.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball combined-stream@1.0.8
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball normalize-range@0.1.2
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball object-assign@4.1.1
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball postcss-value-parser@4.2.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball path-parse@1.0.7
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball delayed-stream@1.0.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball proxy-from-env@1.1.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball loose-envify@1.4.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball pify@2.3.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball glob-parent@5.1.2
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.walk@1.2.8
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball detect-node-es@1.1.0
22.08 
22.08 error: CERT_HAS_EXPIRED downloading tarball babel-plugin-macros@3.1.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.stat@2.0.5
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball find-root@1.1.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball merge2@1.4.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball escape-string-regexp@4.0.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball ms@2.1.3
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball source-map@0.5.7
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball hoist-non-react-statics@3.3.2
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball streamsearch@1.1.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball is-glob@4.0.3
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball @nodelib/fs.scandir@2.1.5
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball js-tokens@4.0.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball color-convert@2.0.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball is-extglob@2.1.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball run-parallel@1.2.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball globals@11.12.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball parse-json@5.2.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball yaml@1.10.2
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball path-type@4.0.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball color-name@1.1.4
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball simple-swizzle@0.2.2
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball queue-microtask@1.2.3
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball to-regex-range@5.0.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball resolve-from@4.0.0
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball json-parse-even-better-errors@2.3.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball lines-and-columns@1.2.4
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball parent-module@1.0.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball is-arrayish@0.3.2
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball is-arrayish@0.2.1
22.09 
22.09 error: CERT_HAS_EXPIRED downloading tarball is-number@7.0.0
22.09 
22.10 error: CERT_HAS_EXPIRED downloading tarball error-ex@1.3.2
22.10 
22.10 error: CERT_HAS_EXPIRED downloading tarball callsites@3.1.0
22.10 Run with --loglevel debug  for the full log.
------
failed to solve: process "/bin/sh -c reflex export --frontend-only --no-zip" did not complete successfully: exit code: 1```

**Comment by adhami3310** [comment]
try setting the npm registry (there's an environment variable for it), i think you might be picking up the Chinese registry for some reason and that one is having ssl problems

i have a fix for it and it should be there for next release

**Comment by borolepratik** [comment]
having used npm instead of bun, seeing no cert errors.

however, i run into these errors. i have only one route - `index`.

```
2025-03-27 22:54:36 ───────────────────────────── Starting Reflex App ──────────────────────────────
2025-03-27 22:54:38 [17:24:37] Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 16/16 0:00:00
2025-03-27 22:54:57 Creating Production Build:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9 0:00:16
2025-03-27 22:54:57 ───────────────────────────────── App Running ──────────────────────────────────
2025-03-27 22:54:59 App running at: http://localhost:54321
2025-03-27 22:54:59 Backend running at: http://0.0.0.0:54322
2025-03-27 22:55:02 Process granian-worker:
2025-03-27 22:55:02 Traceback (most recent call last):
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
2025-03-27 22:55:02     self.run()
2025-03-27 22:55:02     ~~~~~~~~^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/multiprocessing/process.py", line 108, in run
2025-03-27 22:55:02     self._target(*self._args, **self._kwargs)
2025-03-27 22:55:02     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/granian/server/mp.py", line 140, in _spawn_asgi_lifespan_worker
2025-03-27 22:55:02     callback = callback_loader()
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/granian/_internal.py", line 63, in load_target
2025-03-27 22:55:02     rv = rv()
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 582, in __call__
2025-03-27 22:55:02     self._apply_decorated_pages()
2025-03-27 22:55:02     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 1022, in _apply_decorated_pages
2025-03-27 22:55:02     self.add_page(render, **kwargs)
2025-03-27 22:55:02     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 740, in add_page
2025-03-27 22:55:02     raise exceptions.RouteValueError(
2025-03-27 22:55:02     ...<2 lines>...
2025-03-27 22:55:02     )
2025-03-27 22:55:02 reflex.utils.exceptions.RouteValueError: Duplicate page route `index` or `/` already exists. Make sure you do not have two pages with the same route
2025-03-27 22:55:02 Process granian-worker:
2025-03-27 22:55:02 Traceback (most recent call last):
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
2025-03-27 22:55:02     self.run()
2025-03-27 22:55:02     ~~~~~~~~^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/multiprocessing/process.py", line 108, in run
2025-03-27 22:55:02     self._target(*self._args, **self._kwargs)
2025-03-27 22:55:02     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/granian/server/mp.py", line 140, in _spawn_asgi_lifespan_worker
2025-03-27 22:55:02     callback = callback_loader()
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/granian/_internal.py", line 63, in load_target
2025-03-27 22:55:02     rv = rv()
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 582, in __call__
2025-03-27 22:55:02     self._apply_decorated_pages()
2025-03-27 22:55:02     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 1022, in _apply_decorated_pages
2025-03-27 22:55:02     self.add_page(render, **kwargs)
2025-03-27 22:55:02     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-03-27 22:55:02   File "/usr/local/lib/python3.13/site-packages/reflex/app.py", line 740, in add_page
2025-03-27 22:55:02     raise exceptions.RouteValueError(
2025-03-27 22:55:02     ...<2 lines>...
2025-03-27 22:55:02     )
```

**Comment by borolepratik** [comment]
i dont have any config for workers in granian, so unsure about the number of workers being used.
