### ISSUE TITLE
No conexiòn to SQLite

### ISSUE THREAD

**Issue by BryanLitardo312** [reflex-dev/reflex#4569]
Hi,

I'm doing the frontend deploy on vercel y backend on railway, however the conexion is not successfull. It's apppears like it doesn't read the database.

Logs:

Task exception was never retrieved

future: <Task finished name='Task-31' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.11/site-packages/socketio/async_server.py:608> exception=OperationalError('(sqlite3.OperationalError) no such table: localuser')>

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context

    self.dialect.do_execute(

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute

    cursor.execute(statement, parameters)

sqlite3.OperationalError: no such table: localuser

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/socketio/async_server.py", line 610, in _handle_event_internal

    r = await server._trigger_event(data[0], namespace, sid, *data[1:])

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/socketio/async_server.py", line 646, in _trigger_event

    return await handler.trigger_event(event, *args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/socketio/async_namespace.py", line 37, in trigger_event

    ret = await handler(*args)

          ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/app.py", line 1568, in on_event

    async for update in process(self.app, event, sid, headers, client_ip):

  File "/usr/local/lib/python3.11/site-packages/reflex/app.py", line 1286, in process

    update = await app._preprocess(state, event)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/app_mixins/middleware.py", line 56, in _preprocess

    out = await middleware.preprocess(app=self, state=state, event=event)  # type: ignore

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/middleware/hydrate_middleware.py", line 45, in preprocess

    delta = state.dict()

            ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 2058, in dict

    for substate_d in [

                      ^

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 2059, in <listcomp>

    v.dict(include_computed=include_computed, initial=initial, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 2046, in dict

    computed_vars = {

                    ^

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 2048, in <dictcomp>

    prop_name: self.get_value(prop_name)

               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 2006, in get_value

    value = super().get_value(key)

            ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/base.py", line 136, in get_value

    return getattr(self, key, key)

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/state.py", line 1251, in __getattribute__

    value = super().__getattribute__(name)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex/vars/base.py", line 2031, in __get__

    setattr(instance, self._cache_attr, self.fget(instance))

                                        ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/reflex_local_auth/local_auth.py", line 37, in authenticated_user

    result = session.exec(

             ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/sqlmodel/orm/session.py", line 66, in exec

    results = super().execute(

              ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute

    return self._execute_internal(

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal

    result: Result[Any] = compile_state_cls.orm_execute_statement(

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement

    result = conn.execute(

             ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute

**Comment by adhami3310** [comment]
need more to debug this than just that
