### ISSUE TITLE
pynecone.io  Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by monkeycc** [reflex-dev/reflex#713]
`https://pynecone.io/docs/library/forms/radiogroup`
`https://pynecone.io/docs/library/typography/text`
......
Application error: A client exception occurred (see the browser console for more information).
Unable to access some websites normally

```
radiogroup:1 
        
       GET https://pynecone.io/docs/library/forms/radiogroup 404
main-b094e4c872295a17.js:1 

       GET https://www.googletagmanager.com/gtag/js?id=G-4T7C8ZD9TR net::ERR_SSL_PROTOCOL_ERROR
v @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
Ui @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Fi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
ki @ framework-79bce4a3a540b080.js:1
os @ framework-79bce4a3a540b080.js:1
t.hydrate @ framework-79bce4a3a540b080.js:1
h.default.createElement.callbacks @ main-b094e4c872295a17.js:1
oe @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
n @ main-b094e4c872295a17.js:1
u @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
ue @ main-b094e4c872295a17.js:1
ie @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
n @ main-b094e4c872295a17.js:1
u @ main-b094e4c872295a17.js:1
Promise.then(异步)
n @ main-b094e4c872295a17.js:1
u @ main-b094e4c872295a17.js:1
Promise.then(异步)
n @ main-b094e4c872295a17.js:1
u @ main-b094e4c872295a17.js:1
Promise.then(异步)
n @ main-b094e4c872295a17.js:1
u @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
ce @ main-b094e4c872295a17.js:1
t.hydrate @ main-b094e4c872295a17.js:1
(匿名) @ main-b094e4c872295a17.js:1
Promise.then(异步)
22870 @ main-b094e4c872295a17.js:1
n @ webpack-aded48a836863efc.js:1
(匿名) @ main-b094e4c872295a17.js:1
n.O @ webpack-aded48a836863efc.js:1
(匿名) @ main-b094e4c872295a17.js:1
t @ webpack-aded48a836863efc.js:1
(匿名) @ main-b094e4c872295a17.js:1
VM379:2 Edge Translation started
framework-79bce4a3a540b080.js:1 
        
       DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89436)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89541)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at Su (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:88934)
    at Ri (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:101693)
    at t.unstable_runWithPriority (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:129355)
    at Ql (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:44986)
    at Oi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:99854)
    at bi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:95940)
cu @ framework-79bce4a3a540b080.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1
main-b094e4c872295a17.js:1 
        
       DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89436)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89541)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at Su (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:88934)
    at Ri (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:101693)
    at t.unstable_runWithPriority (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:129355)
    at Ql (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:44986)
    at Oi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:99854)
    at bi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:95940)
J @ main-b094e4c872295a17.js:1
fn @ main-b094e4c872295a17.js:1
value @ main-b094e4c872295a17.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1
main-b094e4c872295a17.js:1 
        
       A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
J @ main-b094e4c872295a17.js:1
fn @ main-b094e4c872295a17.js:1
value @ main-b094e4c872295a17.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1
framework-79bce4a3a540b080.js:1 
        
       DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89436)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89541)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at Su (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:88934)
    at Ri (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:101693)
    at t.unstable_runWithPriority (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:129355)
    at Ql (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:44986)
    at Oi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:99854)
    at bi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:95940)
cu @ framework-79bce4a3a540b080.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1
main-b094e4c872295a17.js:1 
        
       DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89436)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89541)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at _u (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:89509)
    at Su (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:88934)
    at Ri (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:101693)
    at t.unstable_runWithPriority (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:129355)
    at Ql (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:44986)
    at Oi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:99854)
    at bi (https://pynecone.io/_next/static/chunks/framework-79bce4a3a540b080.js:1:95940)
J @ main-b094e4c872295a17.js:1
fn @ main-b094e4c872295a17.js:1
value @ main-b094e4c872295a17.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1
main-b094e4c872295a17.js:1 
        
       A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
J @ main-b094e4c872295a17.js:1
fn @ main-b094e4c872295a17.js:1
value @ main-b094e4c872295a17.js:1
a.componentDidCatch.n.callback @ framework-79bce4a3a540b080.js:1
ha @ framework-79bce4a3a540b080.js:1
gu @ framework-79bce4a3a540b080.js:1
Ri @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Oi @ framework-79bce4a3a540b080.js:1
bi @ framework-79bce4a3a540b080.js:1
(匿名) @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Yl @ framework-79bce4a3a540b080.js:1
Kl @ framework-79bce4a3a540b080.js:1
hi @ framework-79bce4a3a540b080.js:1
zo @ framework-79bce4a3a540b080.js:1
(匿名) @ 1064-e3a4f85da95f1b67.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
emitEvent @ 3881-293fc3c50f5c4a78.js:1
onevent @ 3881-293fc3c50f5c4a78.js:1
onpacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
(匿名) @ 3881-293fc3c50f5c4a78.js:1
Promise.then(异步)
(匿名) @ 3881-293fc3c50f5c4a78.js:1
ondecoded @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
add @ 3881-293fc3c50f5c4a78.js:1
ondata @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
y.emit @ 3881-293fc3c50f5c4a78.js:1
onPacket @ 3881-293fc3c50f5c4a78.js:1
onData @ 3881-293fc3c50f5c4a78.js:1
ws.onmessage @ 3881-293fc3c50f5c4a78.js:1

```

**Comment by ElijahAhianyo** [comment]
can confirm this works fine in the latest release, Feel free to reopen if you face further issues
