### ISSUE TITLE
Installation error on Ubuntu 22.04 and python 3.9.6

### ISSUE THREAD

**Issue by Koushik0901** [reflex-dev/reflex#820]
I successfully installed pynecone using `pip install pynecone`
then when I try running `pc init`, I get the following error

```
Traceback (most recent call last):
  File "/home/koushik/miniconda3/envs/myenv/bin/pc", line 5, in <module>
    from pynecone.pc import main
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/pynecone/__init__.py", line 7, in <module>
    from .app import App, UploadFile
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/pynecone/app.py", line 9, in <module>
    from socketio import ASGIApp, AsyncNamespace, AsyncServer
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/engineio/__init__.py", line 8, in <module>
    from .asyncio_client import AsyncClient
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/engineio/asyncio_client.py", line 7, in <module>
    import aiohttp
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/koushik/miniconda3/envs/myenv/lib/python3.9/site-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

**Comment by ElijahAhianyo** [comment]
Is anyone else facing this? I tried this on WSL(ubuntu 20.04) and it works

**Comment by kazeka** [comment]
+1 pyenv virtualenv 3.9.10
