### ISSUE TITLE
Docker images exit after a few seconds

### ISSUE THREAD

**Issue by jq6l43d1** [reflex-dev/reflex#989]
**Describe the bug**
When I create a docker image and run it the image stops running after only a few seconds.

**To Reproduce**
I wrote a bash script to simplify the process of creating and running a simple Pynecone Docker image.
```
#!/bin/bash

rm -rf ~/docker-pynecone-test/*
mkdir -p ~/docker-pynecone-test/hello
cd ~/docker-pynecone-test/
python -m venv venv
source venv/bin/activate
pip install wheel
pip install pynecone
cd hello
pc init
deactivate

echo "import pynecone as pc

config = pc.Config(
    app_name=\"app\",
    api_url=\"0.0.0.0:8000\",
    bun_path=\"/app/.bun/bin/bun\",
    db_url=\"sqlite:///pynecone.db\",
)" > pcconfig.py

echo "pynecone" > requirements.txt

echo "FROM python:3.11-slim as base

RUN adduser --disabled-password pynecone


FROM base as build

WORKDIR /app
ENV VIRTUAL_ENV=/app/venv
RUN python3 -m venv \$VIRTUAL_ENV
ENV PATH=\"\$VIRTUAL_ENV/bin:\$PATH\"

COPY . .

RUN pip install wheel \\
    && pip install -r requirements.txt


FROM base as runtime

RUN apt-get update && apt-get install -y \\
    curl \\
    && curl -fsSL https://deb.nodesource.com/setup_19.x | bash - \\
    && apt-get update && apt-get install -y \\
    nodejs \\
    unzip \\
    && rm -rf /var/lib/apt/lists/*

ENV PATH=\"/app/venv/bin:\$PATH\"


FROM runtime as init

WORKDIR /app
ENV BUN_INSTALL=\"/app/.bun\"
COPY --from=build /app/ /app/
RUN pc init


FROM runtime

COPY --chown=pynecone --from=init /app/ /app/
USER pynecone
WORKDIR /app

CMD [\"pc\",\"run\" , \"--env\", \"prod\"]

EXPOSE 3000
EXPOSE 8000" > Dockerfile

docker build -t pynecone-project:latest .
docker run -d -p 3000:3000 -p 8000:8000 --name pynecone pynecone-project:latest
```

**Expected behavior**
The Docker image should continue to run and be accessible via localhost:3000

**Screenshots**
![image](https://github.com/pynecone-io/pynecone/assets/110377310/de54b85c-0695-46dd-a0a4-2c4024d56fb4)

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.29
 - OS (host): Ubuntu 23.04

**Comment by chrisrosner** [comment]
I don't think it's a bug in pynecone. I tried out your script and used docker log to see:

```
Traceback (most recent call last):
  File "/app/venv/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/pynecone/pc.py", line 117, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'app'
```

Changing app_name from "app" to "hello" (this is what pc init does) resolves this problem.

You're kind of inviting trouble by having a directory named app when you've got a module named app elsewhere in the ecosystem. You should consider naming it after your project/company to avoid problems.

**Comment by chrisrosner** [comment]
Also, this is a minimalist dockerfile that shows you can run pynecone in a docker image (there may be pynecone official images, not sure)

`FROM python:3.11-slim as base

RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_19.x | bash - \
    && apt-get update && apt-get install -y \
    nodejs \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN node --version

RUN pip install pynecone
RUN mkdir /my_app_name
WORKDIR /my_app_name
RUN pc init

CMD ["pc", "run" , "--env", "prod"]

EXPOSE 3000
EXPOSE 8000
`
